// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/teacher.proto

package teacher

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeacherId     string                 `protobuf:"bytes,1,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseRequest) Reset() {
	*x = CreateCourseRequest{}
	mi := &file_proto_teacher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseRequest) ProtoMessage() {}

func (x *CreateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseRequest.ProtoReflect.Descriptor instead.
func (*CreateCourseRequest) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCourseRequest) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *CreateCourseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCourseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseResponse) Reset() {
	*x = CourseResponse{}
	mi := &file_proto_teacher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseResponse) ProtoMessage() {}

func (x *CourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseResponse.ProtoReflect.Descriptor instead.
func (*CourseResponse) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{1}
}

func (x *CourseResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CourseResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type AssignGradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeacherId     string                 `protobuf:"bytes,1,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"` // Security check
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,3,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"` // The UUID from Student Service
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignGradeRequest) Reset() {
	*x = AssignGradeRequest{}
	mi := &file_proto_teacher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignGradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignGradeRequest) ProtoMessage() {}

func (x *AssignGradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignGradeRequest.ProtoReflect.Descriptor instead.
func (*AssignGradeRequest) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{2}
}

func (x *AssignGradeRequest) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *AssignGradeRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *AssignGradeRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *AssignGradeRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type GradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeResponse) Reset() {
	*x = GradeResponse{}
	mi := &file_proto_teacher_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeResponse) ProtoMessage() {}

func (x *GradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeResponse.ProtoReflect.Descriptor instead.
func (*GradeResponse) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{3}
}

func (x *GradeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GradeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetStudentGradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentGradesRequest) Reset() {
	*x = GetStudentGradesRequest{}
	mi := &file_proto_teacher_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentGradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentGradesRequest) ProtoMessage() {}

func (x *GetStudentGradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentGradesRequest.ProtoReflect.Descriptor instead.
func (*GetStudentGradesRequest) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{4}
}

func (x *GetStudentGradesRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type GradeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseTitle   string                 `protobuf:"bytes,1,opt,name=course_title,json=courseTitle,proto3" json:"course_title,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeItem) Reset() {
	*x = GradeItem{}
	mi := &file_proto_teacher_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeItem) ProtoMessage() {}

func (x *GradeItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeItem.ProtoReflect.Descriptor instead.
func (*GradeItem) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{5}
}

func (x *GradeItem) GetCourseTitle() string {
	if x != nil {
		return x.CourseTitle
	}
	return ""
}

func (x *GradeItem) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type StudentGradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grades        []*GradeItem           `protobuf:"bytes,1,rep,name=grades,proto3" json:"grades,omitempty"` // array in proto
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentGradesResponse) Reset() {
	*x = StudentGradesResponse{}
	mi := &file_proto_teacher_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentGradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentGradesResponse) ProtoMessage() {}

func (x *StudentGradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentGradesResponse.ProtoReflect.Descriptor instead.
func (*StudentGradesResponse) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{6}
}

func (x *StudentGradesResponse) GetGrades() []*GradeItem {
	if x != nil {
		return x.Grades
	}
	return nil
}

var File_proto_teacher_proto protoreflect.FileDescriptor

const file_proto_teacher_proto_rawDesc = "" +
	"\n" +
	"\x13proto/teacher.proto\x12\ateacher\"l\n" +
	"\x13CreateCourseRequest\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x01 \x01(\tR\tteacherId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"6\n" +
	"\x0eCourseResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"\x85\x01\n" +
	"\x12AssignGradeRequest\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x01 \x01(\tR\tteacherId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x03 \x01(\tR\tstudentId\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\"9\n" +
	"\rGradeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"8\n" +
	"\x17GetStudentGradesRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\"D\n" +
	"\tGradeItem\x12!\n" +
	"\fcourse_title\x18\x01 \x01(\tR\vcourseTitle\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\"C\n" +
	"\x15StudentGradesResponse\x12*\n" +
	"\x06grades\x18\x01 \x03(\v2\x12.teacher.GradeItemR\x06grades2\xf1\x01\n" +
	"\x0eTeacherService\x12E\n" +
	"\fCreateCourse\x12\x1c.teacher.CreateCourseRequest\x1a\x17.teacher.CourseResponse\x12B\n" +
	"\vAssignGrade\x12\x1b.teacher.AssignGradeRequest\x1a\x16.teacher.GradeResponse\x12T\n" +
	"\x10GetStudentGrades\x12 .teacher.GetStudentGradesRequest\x1a\x1e.teacher.StudentGradesResponseBCZAgithub.com/noxturnedev/lms-monorepo/teacher-service/proto/teacherb\x06proto3"

var (
	file_proto_teacher_proto_rawDescOnce sync.Once
	file_proto_teacher_proto_rawDescData []byte
)

func file_proto_teacher_proto_rawDescGZIP() []byte {
	file_proto_teacher_proto_rawDescOnce.Do(func() {
		file_proto_teacher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_teacher_proto_rawDesc), len(file_proto_teacher_proto_rawDesc)))
	})
	return file_proto_teacher_proto_rawDescData
}

var file_proto_teacher_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_teacher_proto_goTypes = []any{
	(*CreateCourseRequest)(nil),     // 0: teacher.CreateCourseRequest
	(*CourseResponse)(nil),          // 1: teacher.CourseResponse
	(*AssignGradeRequest)(nil),      // 2: teacher.AssignGradeRequest
	(*GradeResponse)(nil),           // 3: teacher.GradeResponse
	(*GetStudentGradesRequest)(nil), // 4: teacher.GetStudentGradesRequest
	(*GradeItem)(nil),               // 5: teacher.GradeItem
	(*StudentGradesResponse)(nil),   // 6: teacher.StudentGradesResponse
}
var file_proto_teacher_proto_depIdxs = []int32{
	5, // 0: teacher.StudentGradesResponse.grades:type_name -> teacher.GradeItem
	0, // 1: teacher.TeacherService.CreateCourse:input_type -> teacher.CreateCourseRequest
	2, // 2: teacher.TeacherService.AssignGrade:input_type -> teacher.AssignGradeRequest
	4, // 3: teacher.TeacherService.GetStudentGrades:input_type -> teacher.GetStudentGradesRequest
	1, // 4: teacher.TeacherService.CreateCourse:output_type -> teacher.CourseResponse
	3, // 5: teacher.TeacherService.AssignGrade:output_type -> teacher.GradeResponse
	6, // 6: teacher.TeacherService.GetStudentGrades:output_type -> teacher.StudentGradesResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_teacher_proto_init() }
func file_proto_teacher_proto_init() {
	if File_proto_teacher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_teacher_proto_rawDesc), len(file_proto_teacher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_teacher_proto_goTypes,
		DependencyIndexes: file_proto_teacher_proto_depIdxs,
		MessageInfos:      file_proto_teacher_proto_msgTypes,
	}.Build()
	File_proto_teacher_proto = out.File
	file_proto_teacher_proto_goTypes = nil
	file_proto_teacher_proto_depIdxs = nil
}
