// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: teacher.proto

package teacher

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeacherId     string                 `protobuf:"bytes,1,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseRequest) Reset() {
	*x = CreateCourseRequest{}
	mi := &file_teacher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseRequest) ProtoMessage() {}

func (x *CreateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseRequest.ProtoReflect.Descriptor instead.
func (*CreateCourseRequest) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCourseRequest) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *CreateCourseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCourseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseResponse) Reset() {
	*x = CourseResponse{}
	mi := &file_teacher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseResponse) ProtoMessage() {}

func (x *CourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseResponse.ProtoReflect.Descriptor instead.
func (*CourseResponse) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{1}
}

func (x *CourseResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CourseResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type AssignGradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeacherId     string                 `protobuf:"bytes,1,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"` // Security check
	AssignmentId  string                 `protobuf:"bytes,2,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,3,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"` // The UUID from Student Service
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignGradeRequest) Reset() {
	*x = AssignGradeRequest{}
	mi := &file_teacher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignGradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignGradeRequest) ProtoMessage() {}

func (x *AssignGradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignGradeRequest.ProtoReflect.Descriptor instead.
func (*AssignGradeRequest) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{2}
}

func (x *AssignGradeRequest) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *AssignGradeRequest) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *AssignGradeRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *AssignGradeRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type GradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeResponse) Reset() {
	*x = GradeResponse{}
	mi := &file_teacher_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeResponse) ProtoMessage() {}

func (x *GradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeResponse.ProtoReflect.Descriptor instead.
func (*GradeResponse) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{3}
}

func (x *GradeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GradeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetStudentGradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentGradesRequest) Reset() {
	*x = GetStudentGradesRequest{}
	mi := &file_teacher_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentGradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentGradesRequest) ProtoMessage() {}

func (x *GetStudentGradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentGradesRequest.ProtoReflect.Descriptor instead.
func (*GetStudentGradesRequest) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{4}
}

func (x *GetStudentGradesRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type GradeItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CourseTitle     string                 `protobuf:"bytes,1,opt,name=course_title,json=courseTitle,proto3" json:"course_title,omitempty"`
	Score           int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	AssignmentTitle string                 `protobuf:"bytes,3,opt,name=assignment_title,json=assignmentTitle,proto3" json:"assignment_title,omitempty"`
	MaxScore        int32                  `protobuf:"varint,4,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	AssignmentId    string                 `protobuf:"bytes,5,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GradeItem) Reset() {
	*x = GradeItem{}
	mi := &file_teacher_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeItem) ProtoMessage() {}

func (x *GradeItem) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeItem.ProtoReflect.Descriptor instead.
func (*GradeItem) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{5}
}

func (x *GradeItem) GetCourseTitle() string {
	if x != nil {
		return x.CourseTitle
	}
	return ""
}

func (x *GradeItem) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GradeItem) GetAssignmentTitle() string {
	if x != nil {
		return x.AssignmentTitle
	}
	return ""
}

func (x *GradeItem) GetMaxScore() int32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

func (x *GradeItem) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

type StudentGradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grades        []*GradeItem           `protobuf:"bytes,1,rep,name=grades,proto3" json:"grades,omitempty"` // array in proto
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentGradesResponse) Reset() {
	*x = StudentGradesResponse{}
	mi := &file_teacher_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentGradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentGradesResponse) ProtoMessage() {}

func (x *StudentGradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentGradesResponse.ProtoReflect.Descriptor instead.
func (*StudentGradesResponse) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{6}
}

func (x *StudentGradesResponse) GetGrades() []*GradeItem {
	if x != nil {
		return x.Grades
	}
	return nil
}

// Authentication Messages
type LoginTeacherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginTeacherRequest) Reset() {
	*x = LoginTeacherRequest{}
	mi := &file_teacher_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginTeacherRequest) ProtoMessage() {}

func (x *LoginTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginTeacherRequest.ProtoReflect.Descriptor instead.
func (*LoginTeacherRequest) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{7}
}

func (x *LoginTeacherRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginTeacherRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginTeacherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TeacherId     string                 `protobuf:"bytes,3,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,5,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginTeacherResponse) Reset() {
	*x = LoginTeacherResponse{}
	mi := &file_teacher_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginTeacherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginTeacherResponse) ProtoMessage() {}

func (x *LoginTeacherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginTeacherResponse.ProtoReflect.Descriptor instead.
func (*LoginTeacherResponse) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{8}
}

func (x *LoginTeacherResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginTeacherResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginTeacherResponse) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *LoginTeacherResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginTeacherResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

// Teacher CRUD Messages
type CreateTeacherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeacherRequest) Reset() {
	*x = CreateTeacherRequest{}
	mi := &file_teacher_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeacherRequest) ProtoMessage() {}

func (x *CreateTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeacherRequest.ProtoReflect.Descriptor instead.
func (*CreateTeacherRequest) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{9}
}

func (x *CreateTeacherRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateTeacherRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateTeacherRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

type GetTeacherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeacherRequest) Reset() {
	*x = GetTeacherRequest{}
	mi := &file_teacher_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeacherRequest) ProtoMessage() {}

func (x *GetTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeacherRequest.ProtoReflect.Descriptor instead.
func (*GetTeacherRequest) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{10}
}

func (x *GetTeacherRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateTeacherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeacherRequest) Reset() {
	*x = UpdateTeacherRequest{}
	mi := &file_teacher_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeacherRequest) ProtoMessage() {}

func (x *UpdateTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeacherRequest.ProtoReflect.Descriptor instead.
func (*UpdateTeacherRequest) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateTeacherRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTeacherRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateTeacherRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UpdateTeacherRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type DeleteTeacherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeacherRequest) Reset() {
	*x = DeleteTeacherRequest{}
	mi := &file_teacher_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeacherRequest) ProtoMessage() {}

func (x *DeleteTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeacherRequest.ProtoReflect.Descriptor instead.
func (*DeleteTeacherRequest) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteTeacherRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTeacherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeacherResponse) Reset() {
	*x = DeleteTeacherResponse{}
	mi := &file_teacher_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeacherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeacherResponse) ProtoMessage() {}

func (x *DeleteTeacherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeacherResponse.ProtoReflect.Descriptor instead.
func (*DeleteTeacherResponse) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteTeacherResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListTeachersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeachersRequest) Reset() {
	*x = ListTeachersRequest{}
	mi := &file_teacher_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeachersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeachersRequest) ProtoMessage() {}

func (x *ListTeachersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeachersRequest.ProtoReflect.Descriptor instead.
func (*ListTeachersRequest) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{14}
}

type TeacherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeacherResponse) Reset() {
	*x = TeacherResponse{}
	mi := &file_teacher_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeacherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeacherResponse) ProtoMessage() {}

func (x *TeacherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeacherResponse.ProtoReflect.Descriptor instead.
func (*TeacherResponse) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{15}
}

func (x *TeacherResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TeacherResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TeacherResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

type ListTeachersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teachers      []*TeacherResponse     `protobuf:"bytes,1,rep,name=teachers,proto3" json:"teachers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeachersResponse) Reset() {
	*x = ListTeachersResponse{}
	mi := &file_teacher_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeachersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeachersResponse) ProtoMessage() {}

func (x *ListTeachersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeachersResponse.ProtoReflect.Descriptor instead.
func (*ListTeachersResponse) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{16}
}

func (x *ListTeachersResponse) GetTeachers() []*TeacherResponse {
	if x != nil {
		return x.Teachers
	}
	return nil
}

// Course Management Messages
type GetCoursesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeacherId     string                 `protobuf:"bytes,1,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoursesRequest) Reset() {
	*x = GetCoursesRequest{}
	mi := &file_teacher_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoursesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesRequest) ProtoMessage() {}

func (x *GetCoursesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesRequest.ProtoReflect.Descriptor instead.
func (*GetCoursesRequest) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{17}
}

func (x *GetCoursesRequest) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

type GetCoursesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Courses       []*CourseDetailResponse `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoursesResponse) Reset() {
	*x = GetCoursesResponse{}
	mi := &file_teacher_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoursesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesResponse) ProtoMessage() {}

func (x *GetCoursesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesResponse.ProtoReflect.Descriptor instead.
func (*GetCoursesResponse) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{18}
}

func (x *GetCoursesResponse) GetCourses() []*CourseDetailResponse {
	if x != nil {
		return x.Courses
	}
	return nil
}

type GetCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseRequest) Reset() {
	*x = GetCourseRequest{}
	mi := &file_teacher_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseRequest) ProtoMessage() {}

func (x *GetCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseRequest.ProtoReflect.Descriptor instead.
func (*GetCourseRequest) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{19}
}

func (x *GetCourseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CourseDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TeacherId     string                 `protobuf:"bytes,2,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	TeacherName   string                 `protobuf:"bytes,5,opt,name=teacher_name,json=teacherName,proto3" json:"teacher_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseDetailResponse) Reset() {
	*x = CourseDetailResponse{}
	mi := &file_teacher_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseDetailResponse) ProtoMessage() {}

func (x *CourseDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseDetailResponse.ProtoReflect.Descriptor instead.
func (*CourseDetailResponse) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{20}
}

func (x *CourseDetailResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CourseDetailResponse) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *CourseDetailResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CourseDetailResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CourseDetailResponse) GetTeacherName() string {
	if x != nil {
		return x.TeacherName
	}
	return ""
}

type UpdateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseRequest) Reset() {
	*x = UpdateCourseRequest{}
	mi := &file_teacher_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseRequest) ProtoMessage() {}

func (x *UpdateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseRequest.ProtoReflect.Descriptor instead.
func (*UpdateCourseRequest) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateCourseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCourseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateCourseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeleteCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseRequest) Reset() {
	*x = DeleteCourseRequest{}
	mi := &file_teacher_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseRequest) ProtoMessage() {}

func (x *DeleteCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseRequest.ProtoReflect.Descriptor instead.
func (*DeleteCourseRequest) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteCourseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseResponse) Reset() {
	*x = DeleteCourseResponse{}
	mi := &file_teacher_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseResponse) ProtoMessage() {}

func (x *DeleteCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseResponse.ProtoReflect.Descriptor instead.
func (*DeleteCourseResponse) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteCourseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteCourseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Assignment Messages
type CreateAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MaxScore      int32                  `protobuf:"varint,4,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssignmentRequest) Reset() {
	*x = CreateAssignmentRequest{}
	mi := &file_teacher_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssignmentRequest) ProtoMessage() {}

func (x *CreateAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssignmentRequest.ProtoReflect.Descriptor instead.
func (*CreateAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{24}
}

func (x *CreateAssignmentRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CreateAssignmentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAssignmentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAssignmentRequest) GetMaxScore() int32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

type AssignmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	MaxScore      int32                  `protobuf:"varint,3,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignmentResponse) Reset() {
	*x = AssignmentResponse{}
	mi := &file_teacher_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignmentResponse) ProtoMessage() {}

func (x *AssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignmentResponse.ProtoReflect.Descriptor instead.
func (*AssignmentResponse) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{25}
}

func (x *AssignmentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AssignmentResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AssignmentResponse) GetMaxScore() int32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

type GetAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssignmentRequest) Reset() {
	*x = GetAssignmentRequest{}
	mi := &file_teacher_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssignmentRequest) ProtoMessage() {}

func (x *GetAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssignmentRequest.ProtoReflect.Descriptor instead.
func (*GetAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{26}
}

func (x *GetAssignmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AssignmentDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	CourseTitle   string                 `protobuf:"bytes,3,opt,name=course_title,json=courseTitle,proto3" json:"course_title,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	MaxScore      int32                  `protobuf:"varint,6,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignmentDetailResponse) Reset() {
	*x = AssignmentDetailResponse{}
	mi := &file_teacher_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignmentDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignmentDetailResponse) ProtoMessage() {}

func (x *AssignmentDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignmentDetailResponse.ProtoReflect.Descriptor instead.
func (*AssignmentDetailResponse) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{27}
}

func (x *AssignmentDetailResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AssignmentDetailResponse) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *AssignmentDetailResponse) GetCourseTitle() string {
	if x != nil {
		return x.CourseTitle
	}
	return ""
}

func (x *AssignmentDetailResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AssignmentDetailResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AssignmentDetailResponse) GetMaxScore() int32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

type UpdateAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MaxScore      int32                  `protobuf:"varint,4,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAssignmentRequest) Reset() {
	*x = UpdateAssignmentRequest{}
	mi := &file_teacher_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssignmentRequest) ProtoMessage() {}

func (x *UpdateAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssignmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateAssignmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAssignmentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateAssignmentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateAssignmentRequest) GetMaxScore() int32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

type DeleteAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssignmentRequest) Reset() {
	*x = DeleteAssignmentRequest{}
	mi := &file_teacher_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssignmentRequest) ProtoMessage() {}

func (x *DeleteAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssignmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteAssignmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAssignmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssignmentResponse) Reset() {
	*x = DeleteAssignmentResponse{}
	mi := &file_teacher_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssignmentResponse) ProtoMessage() {}

func (x *DeleteAssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssignmentResponse.ProtoReflect.Descriptor instead.
func (*DeleteAssignmentResponse) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteAssignmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteAssignmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListAssignmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssignmentsRequest) Reset() {
	*x = ListAssignmentsRequest{}
	mi := &file_teacher_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssignmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssignmentsRequest) ProtoMessage() {}

func (x *ListAssignmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssignmentsRequest.ProtoReflect.Descriptor instead.
func (*ListAssignmentsRequest) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{31}
}

func (x *ListAssignmentsRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type ListAssignmentsResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Assignments   []*AssignmentDetailResponse `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssignmentsResponse) Reset() {
	*x = ListAssignmentsResponse{}
	mi := &file_teacher_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssignmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssignmentsResponse) ProtoMessage() {}

func (x *ListAssignmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssignmentsResponse.ProtoReflect.Descriptor instead.
func (*ListAssignmentsResponse) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{32}
}

func (x *ListAssignmentsResponse) GetAssignments() []*AssignmentDetailResponse {
	if x != nil {
		return x.Assignments
	}
	return nil
}

// Student Course Grade Messages
type GetStudentCourseGradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentCourseGradeRequest) Reset() {
	*x = GetStudentCourseGradeRequest{}
	mi := &file_teacher_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentCourseGradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentCourseGradeRequest) ProtoMessage() {}

func (x *GetStudentCourseGradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentCourseGradeRequest.ProtoReflect.Descriptor instead.
func (*GetStudentCourseGradeRequest) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{33}
}

func (x *GetStudentCourseGradeRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *GetStudentCourseGradeRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type AssignmentGradeItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId    string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	AssignmentTitle string                 `protobuf:"bytes,2,opt,name=assignment_title,json=assignmentTitle,proto3" json:"assignment_title,omitempty"`
	Score           int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	MaxScore        int32                  `protobuf:"varint,4,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AssignmentGradeItem) Reset() {
	*x = AssignmentGradeItem{}
	mi := &file_teacher_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignmentGradeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignmentGradeItem) ProtoMessage() {}

func (x *AssignmentGradeItem) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignmentGradeItem.ProtoReflect.Descriptor instead.
func (*AssignmentGradeItem) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{34}
}

func (x *AssignmentGradeItem) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *AssignmentGradeItem) GetAssignmentTitle() string {
	if x != nil {
		return x.AssignmentTitle
	}
	return ""
}

func (x *AssignmentGradeItem) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *AssignmentGradeItem) GetMaxScore() int32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

type StudentCourseGradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	CourseTitle   string                 `protobuf:"bytes,2,opt,name=course_title,json=courseTitle,proto3" json:"course_title,omitempty"`
	StudentId     string                 `protobuf:"bytes,3,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	OverallScore  float64                `protobuf:"fixed64,4,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`
	TotalScore    int32                  `protobuf:"varint,5,opt,name=total_score,json=totalScore,proto3" json:"total_score,omitempty"`
	TotalMaxScore int32                  `protobuf:"varint,6,opt,name=total_max_score,json=totalMaxScore,proto3" json:"total_max_score,omitempty"`
	Assignments   []*AssignmentGradeItem `protobuf:"bytes,7,rep,name=assignments,proto3" json:"assignments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentCourseGradeResponse) Reset() {
	*x = StudentCourseGradeResponse{}
	mi := &file_teacher_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentCourseGradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentCourseGradeResponse) ProtoMessage() {}

func (x *StudentCourseGradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentCourseGradeResponse.ProtoReflect.Descriptor instead.
func (*StudentCourseGradeResponse) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{35}
}

func (x *StudentCourseGradeResponse) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *StudentCourseGradeResponse) GetCourseTitle() string {
	if x != nil {
		return x.CourseTitle
	}
	return ""
}

func (x *StudentCourseGradeResponse) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *StudentCourseGradeResponse) GetOverallScore() float64 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

func (x *StudentCourseGradeResponse) GetTotalScore() int32 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

func (x *StudentCourseGradeResponse) GetTotalMaxScore() int32 {
	if x != nil {
		return x.TotalMaxScore
	}
	return 0
}

func (x *StudentCourseGradeResponse) GetAssignments() []*AssignmentGradeItem {
	if x != nil {
		return x.Assignments
	}
	return nil
}

// Enrollment Messages
type EnrollStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollStudentRequest) Reset() {
	*x = EnrollStudentRequest{}
	mi := &file_teacher_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollStudentRequest) ProtoMessage() {}

func (x *EnrollStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollStudentRequest.ProtoReflect.Descriptor instead.
func (*EnrollStudentRequest) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{36}
}

func (x *EnrollStudentRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *EnrollStudentRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type EnrollmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollmentResponse) Reset() {
	*x = EnrollmentResponse{}
	mi := &file_teacher_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentResponse) ProtoMessage() {}

func (x *EnrollmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentResponse.ProtoReflect.Descriptor instead.
func (*EnrollmentResponse) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{37}
}

func (x *EnrollmentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EnrollmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnrollmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetCourseEnrollmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseEnrollmentsRequest) Reset() {
	*x = GetCourseEnrollmentsRequest{}
	mi := &file_teacher_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseEnrollmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseEnrollmentsRequest) ProtoMessage() {}

func (x *GetCourseEnrollmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseEnrollmentsRequest.ProtoReflect.Descriptor instead.
func (*GetCourseEnrollmentsRequest) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{38}
}

func (x *GetCourseEnrollmentsRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type EnrollmentItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StudentName   string                 `protobuf:"bytes,2,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	StudentNumber string                 `protobuf:"bytes,3,opt,name=student_number,json=studentNumber,proto3" json:"student_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollmentItem) Reset() {
	*x = EnrollmentItem{}
	mi := &file_teacher_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentItem) ProtoMessage() {}

func (x *EnrollmentItem) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentItem.ProtoReflect.Descriptor instead.
func (*EnrollmentItem) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{39}
}

func (x *EnrollmentItem) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *EnrollmentItem) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *EnrollmentItem) GetStudentNumber() string {
	if x != nil {
		return x.StudentNumber
	}
	return ""
}

type GetCourseEnrollmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enrollments   []*EnrollmentItem      `protobuf:"bytes,1,rep,name=enrollments,proto3" json:"enrollments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseEnrollmentsResponse) Reset() {
	*x = GetCourseEnrollmentsResponse{}
	mi := &file_teacher_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseEnrollmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseEnrollmentsResponse) ProtoMessage() {}

func (x *GetCourseEnrollmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseEnrollmentsResponse.ProtoReflect.Descriptor instead.
func (*GetCourseEnrollmentsResponse) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{40}
}

func (x *GetCourseEnrollmentsResponse) GetEnrollments() []*EnrollmentItem {
	if x != nil {
		return x.Enrollments
	}
	return nil
}

// Gradebook Messages
type GetCourseGradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseGradesRequest) Reset() {
	*x = GetCourseGradesRequest{}
	mi := &file_teacher_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseGradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseGradesRequest) ProtoMessage() {}

func (x *GetCourseGradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseGradesRequest.ProtoReflect.Descriptor instead.
func (*GetCourseGradesRequest) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{41}
}

func (x *GetCourseGradesRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type StudentGradeItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StudentId       string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StudentName     string                 `protobuf:"bytes,2,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	StudentNumber   string                 `protobuf:"bytes,3,opt,name=student_number,json=studentNumber,proto3" json:"student_number,omitempty"`
	Score           int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	GradeId         string                 `protobuf:"bytes,5,opt,name=grade_id,json=gradeId,proto3" json:"grade_id,omitempty"`
	AssignmentTitle string                 `protobuf:"bytes,6,opt,name=assignment_title,json=assignmentTitle,proto3" json:"assignment_title,omitempty"`
	MaxScore        int32                  `protobuf:"varint,7,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	AssignmentId    string                 `protobuf:"bytes,8,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StudentGradeItem) Reset() {
	*x = StudentGradeItem{}
	mi := &file_teacher_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentGradeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentGradeItem) ProtoMessage() {}

func (x *StudentGradeItem) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentGradeItem.ProtoReflect.Descriptor instead.
func (*StudentGradeItem) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{42}
}

func (x *StudentGradeItem) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *StudentGradeItem) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *StudentGradeItem) GetStudentNumber() string {
	if x != nil {
		return x.StudentNumber
	}
	return ""
}

func (x *StudentGradeItem) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *StudentGradeItem) GetGradeId() string {
	if x != nil {
		return x.GradeId
	}
	return ""
}

func (x *StudentGradeItem) GetAssignmentTitle() string {
	if x != nil {
		return x.AssignmentTitle
	}
	return ""
}

func (x *StudentGradeItem) GetMaxScore() int32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

func (x *StudentGradeItem) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

type CourseGradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	CourseTitle   string                 `protobuf:"bytes,2,opt,name=course_title,json=courseTitle,proto3" json:"course_title,omitempty"`
	Grades        []*StudentGradeItem    `protobuf:"bytes,3,rep,name=grades,proto3" json:"grades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseGradesResponse) Reset() {
	*x = CourseGradesResponse{}
	mi := &file_teacher_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseGradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseGradesResponse) ProtoMessage() {}

func (x *CourseGradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseGradesResponse.ProtoReflect.Descriptor instead.
func (*CourseGradesResponse) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{43}
}

func (x *CourseGradesResponse) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CourseGradesResponse) GetCourseTitle() string {
	if x != nil {
		return x.CourseTitle
	}
	return ""
}

func (x *CourseGradesResponse) GetGrades() []*StudentGradeItem {
	if x != nil {
		return x.Grades
	}
	return nil
}

// Dashboard Messages
type GetTeacherDashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeacherId     string                 `protobuf:"bytes,1,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeacherDashboardRequest) Reset() {
	*x = GetTeacherDashboardRequest{}
	mi := &file_teacher_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeacherDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeacherDashboardRequest) ProtoMessage() {}

func (x *GetTeacherDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeacherDashboardRequest.ProtoReflect.Descriptor instead.
func (*GetTeacherDashboardRequest) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{44}
}

func (x *GetTeacherDashboardRequest) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

type TeacherDashboardResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TeacherId             string                 `protobuf:"bytes,1,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	TeacherName           string                 `protobuf:"bytes,2,opt,name=teacher_name,json=teacherName,proto3" json:"teacher_name,omitempty"`
	TotalCourses          int32                  `protobuf:"varint,3,opt,name=total_courses,json=totalCourses,proto3" json:"total_courses,omitempty"`
	TotalStudentsEnrolled int32                  `protobuf:"varint,4,opt,name=total_students_enrolled,json=totalStudentsEnrolled,proto3" json:"total_students_enrolled,omitempty"`
	Courses               []*CourseSummary       `protobuf:"bytes,5,rep,name=courses,proto3" json:"courses,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TeacherDashboardResponse) Reset() {
	*x = TeacherDashboardResponse{}
	mi := &file_teacher_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeacherDashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeacherDashboardResponse) ProtoMessage() {}

func (x *TeacherDashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeacherDashboardResponse.ProtoReflect.Descriptor instead.
func (*TeacherDashboardResponse) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{45}
}

func (x *TeacherDashboardResponse) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *TeacherDashboardResponse) GetTeacherName() string {
	if x != nil {
		return x.TeacherName
	}
	return ""
}

func (x *TeacherDashboardResponse) GetTotalCourses() int32 {
	if x != nil {
		return x.TotalCourses
	}
	return 0
}

func (x *TeacherDashboardResponse) GetTotalStudentsEnrolled() int32 {
	if x != nil {
		return x.TotalStudentsEnrolled
	}
	return 0
}

func (x *TeacherDashboardResponse) GetCourses() []*CourseSummary {
	if x != nil {
		return x.Courses
	}
	return nil
}

type CourseSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	EnrolledCount int32                  `protobuf:"varint,3,opt,name=enrolled_count,json=enrolledCount,proto3" json:"enrolled_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseSummary) Reset() {
	*x = CourseSummary{}
	mi := &file_teacher_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseSummary) ProtoMessage() {}

func (x *CourseSummary) ProtoReflect() protoreflect.Message {
	mi := &file_teacher_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseSummary.ProtoReflect.Descriptor instead.
func (*CourseSummary) Descriptor() ([]byte, []int) {
	return file_teacher_proto_rawDescGZIP(), []int{46}
}

func (x *CourseSummary) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CourseSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CourseSummary) GetEnrolledCount() int32 {
	if x != nil {
		return x.EnrolledCount
	}
	return 0
}

var File_teacher_proto protoreflect.FileDescriptor

const file_teacher_proto_rawDesc = "" +
	"\n" +
	"\rteacher.proto\x12\ateacher\"l\n" +
	"\x13CreateCourseRequest\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x01 \x01(\tR\tteacherId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"6\n" +
	"\x0eCourseResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"\x8d\x01\n" +
	"\x12AssignGradeRequest\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x01 \x01(\tR\tteacherId\x12#\n" +
	"\rassignment_id\x18\x02 \x01(\tR\fassignmentId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x03 \x01(\tR\tstudentId\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\"9\n" +
	"\rGradeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"8\n" +
	"\x17GetStudentGradesRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\"\xb1\x01\n" +
	"\tGradeItem\x12!\n" +
	"\fcourse_title\x18\x01 \x01(\tR\vcourseTitle\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12)\n" +
	"\x10assignment_title\x18\x03 \x01(\tR\x0fassignmentTitle\x12\x1b\n" +
	"\tmax_score\x18\x04 \x01(\x05R\bmaxScore\x12#\n" +
	"\rassignment_id\x18\x05 \x01(\tR\fassignmentId\"C\n" +
	"\x15StudentGradesResponse\x12*\n" +
	"\x06grades\x18\x01 \x03(\v2\x12.teacher.GradeItemR\x06grades\"G\n" +
	"\x13LoginTeacherRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x9c\x01\n" +
	"\x14LoginTeacherResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x03 \x01(\tR\tteacherId\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x05 \x01(\tR\bfullName\"e\n" +
	"\x14CreateTeacherRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\"#\n" +
	"\x11GetTeacherRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"u\n" +
	"\x14UpdateTeacherRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"&\n" +
	"\x14DeleteTeacherRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteTeacherResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x15\n" +
	"\x13ListTeachersRequest\"T\n" +
	"\x0fTeacherResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\"L\n" +
	"\x14ListTeachersResponse\x124\n" +
	"\bteachers\x18\x01 \x03(\v2\x18.teacher.TeacherResponseR\bteachers\"2\n" +
	"\x11GetCoursesRequest\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x01 \x01(\tR\tteacherId\"M\n" +
	"\x12GetCoursesResponse\x127\n" +
	"\acourses\x18\x01 \x03(\v2\x1d.teacher.CourseDetailResponseR\acourses\"\"\n" +
	"\x10GetCourseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa0\x01\n" +
	"\x14CourseDetailResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x02 \x01(\tR\tteacherId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12!\n" +
	"\fteacher_name\x18\x05 \x01(\tR\vteacherName\"]\n" +
	"\x13UpdateCourseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"%\n" +
	"\x13DeleteCourseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x14DeleteCourseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8b\x01\n" +
	"\x17CreateAssignmentRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tmax_score\x18\x04 \x01(\x05R\bmaxScore\"W\n" +
	"\x12AssignmentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tmax_score\x18\x03 \x01(\x05R\bmaxScore\"&\n" +
	"\x14GetAssignmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xbf\x01\n" +
	"\x18AssignmentDetailResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12!\n" +
	"\fcourse_title\x18\x03 \x01(\tR\vcourseTitle\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1b\n" +
	"\tmax_score\x18\x06 \x01(\x05R\bmaxScore\"~\n" +
	"\x17UpdateAssignmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tmax_score\x18\x04 \x01(\x05R\bmaxScore\")\n" +
	"\x17DeleteAssignmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"N\n" +
	"\x18DeleteAssignmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"5\n" +
	"\x16ListAssignmentsRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"^\n" +
	"\x17ListAssignmentsResponse\x12C\n" +
	"\vassignments\x18\x01 \x03(\v2!.teacher.AssignmentDetailResponseR\vassignments\"Z\n" +
	"\x1cGetStudentCourseGradeRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\"\x98\x01\n" +
	"\x13AssignmentGradeItem\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12)\n" +
	"\x10assignment_title\x18\x02 \x01(\tR\x0fassignmentTitle\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x1b\n" +
	"\tmax_score\x18\x04 \x01(\x05R\bmaxScore\"\xa9\x02\n" +
	"\x1aStudentCourseGradeResponse\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12!\n" +
	"\fcourse_title\x18\x02 \x01(\tR\vcourseTitle\x12\x1d\n" +
	"\n" +
	"student_id\x18\x03 \x01(\tR\tstudentId\x12#\n" +
	"\roverall_score\x18\x04 \x01(\x01R\foverallScore\x12\x1f\n" +
	"\vtotal_score\x18\x05 \x01(\x05R\n" +
	"totalScore\x12&\n" +
	"\x0ftotal_max_score\x18\x06 \x01(\x05R\rtotalMaxScore\x12>\n" +
	"\vassignments\x18\a \x03(\v2\x1c.teacher.AssignmentGradeItemR\vassignments\"R\n" +
	"\x14EnrollStudentRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"X\n" +
	"\x12EnrollmentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\":\n" +
	"\x1bGetCourseEnrollmentsRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"y\n" +
	"\x0eEnrollmentItem\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12!\n" +
	"\fstudent_name\x18\x02 \x01(\tR\vstudentName\x12%\n" +
	"\x0estudent_number\x18\x03 \x01(\tR\rstudentNumber\"Y\n" +
	"\x1cGetCourseEnrollmentsResponse\x129\n" +
	"\venrollments\x18\x01 \x03(\v2\x17.teacher.EnrollmentItemR\venrollments\"5\n" +
	"\x16GetCourseGradesRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"\x99\x02\n" +
	"\x10StudentGradeItem\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12!\n" +
	"\fstudent_name\x18\x02 \x01(\tR\vstudentName\x12%\n" +
	"\x0estudent_number\x18\x03 \x01(\tR\rstudentNumber\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x12\x19\n" +
	"\bgrade_id\x18\x05 \x01(\tR\agradeId\x12)\n" +
	"\x10assignment_title\x18\x06 \x01(\tR\x0fassignmentTitle\x12\x1b\n" +
	"\tmax_score\x18\a \x01(\x05R\bmaxScore\x12#\n" +
	"\rassignment_id\x18\b \x01(\tR\fassignmentId\"\x89\x01\n" +
	"\x14CourseGradesResponse\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12!\n" +
	"\fcourse_title\x18\x02 \x01(\tR\vcourseTitle\x121\n" +
	"\x06grades\x18\x03 \x03(\v2\x19.teacher.StudentGradeItemR\x06grades\";\n" +
	"\x1aGetTeacherDashboardRequest\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x01 \x01(\tR\tteacherId\"\xeb\x01\n" +
	"\x18TeacherDashboardResponse\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x01 \x01(\tR\tteacherId\x12!\n" +
	"\fteacher_name\x18\x02 \x01(\tR\vteacherName\x12#\n" +
	"\rtotal_courses\x18\x03 \x01(\x05R\ftotalCourses\x126\n" +
	"\x17total_students_enrolled\x18\x04 \x01(\x05R\x15totalStudentsEnrolled\x120\n" +
	"\acourses\x18\x05 \x03(\v2\x16.teacher.CourseSummaryR\acourses\"i\n" +
	"\rCourseSummary\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\x0eenrolled_count\x18\x03 \x01(\x05R\renrolledCount2\xc6\x0e\n" +
	"\x0eTeacherService\x12K\n" +
	"\fLoginTeacher\x12\x1c.teacher.LoginTeacherRequest\x1a\x1d.teacher.LoginTeacherResponse\x12H\n" +
	"\rCreateTeacher\x12\x1d.teacher.CreateTeacherRequest\x1a\x18.teacher.TeacherResponse\x12B\n" +
	"\n" +
	"GetTeacher\x12\x1a.teacher.GetTeacherRequest\x1a\x18.teacher.TeacherResponse\x12H\n" +
	"\rUpdateTeacher\x12\x1d.teacher.UpdateTeacherRequest\x1a\x18.teacher.TeacherResponse\x12N\n" +
	"\rDeleteTeacher\x12\x1d.teacher.DeleteTeacherRequest\x1a\x1e.teacher.DeleteTeacherResponse\x12K\n" +
	"\fListTeachers\x12\x1c.teacher.ListTeachersRequest\x1a\x1d.teacher.ListTeachersResponse\x12E\n" +
	"\fCreateCourse\x12\x1c.teacher.CreateCourseRequest\x1a\x17.teacher.CourseResponse\x12E\n" +
	"\n" +
	"GetCourses\x12\x1a.teacher.GetCoursesRequest\x1a\x1b.teacher.GetCoursesResponse\x12E\n" +
	"\tGetCourse\x12\x19.teacher.GetCourseRequest\x1a\x1d.teacher.CourseDetailResponse\x12E\n" +
	"\fUpdateCourse\x12\x1c.teacher.UpdateCourseRequest\x1a\x17.teacher.CourseResponse\x12K\n" +
	"\fDeleteCourse\x12\x1c.teacher.DeleteCourseRequest\x1a\x1d.teacher.DeleteCourseResponse\x12Q\n" +
	"\x10CreateAssignment\x12 .teacher.CreateAssignmentRequest\x1a\x1b.teacher.AssignmentResponse\x12Q\n" +
	"\rGetAssignment\x12\x1d.teacher.GetAssignmentRequest\x1a!.teacher.AssignmentDetailResponse\x12Q\n" +
	"\x10UpdateAssignment\x12 .teacher.UpdateAssignmentRequest\x1a\x1b.teacher.AssignmentResponse\x12W\n" +
	"\x10DeleteAssignment\x12 .teacher.DeleteAssignmentRequest\x1a!.teacher.DeleteAssignmentResponse\x12T\n" +
	"\x0fListAssignments\x12\x1f.teacher.ListAssignmentsRequest\x1a .teacher.ListAssignmentsResponse\x12K\n" +
	"\rEnrollStudent\x12\x1d.teacher.EnrollStudentRequest\x1a\x1b.teacher.EnrollmentResponse\x12c\n" +
	"\x14GetCourseEnrollments\x12$.teacher.GetCourseEnrollmentsRequest\x1a%.teacher.GetCourseEnrollmentsResponse\x12B\n" +
	"\vAssignGrade\x12\x1b.teacher.AssignGradeRequest\x1a\x16.teacher.GradeResponse\x12T\n" +
	"\x10GetStudentGrades\x12 .teacher.GetStudentGradesRequest\x1a\x1e.teacher.StudentGradesResponse\x12Q\n" +
	"\x0fGetCourseGrades\x12\x1f.teacher.GetCourseGradesRequest\x1a\x1d.teacher.CourseGradesResponse\x12c\n" +
	"\x15GetStudentCourseGrade\x12%.teacher.GetStudentCourseGradeRequest\x1a#.teacher.StudentCourseGradeResponse\x12]\n" +
	"\x13GetTeacherDashboard\x12#.teacher.GetTeacherDashboardRequest\x1a!.teacher.TeacherDashboardResponseBCZAgithub.com/noxturnedev/lms-monorepo/teacher-service/proto/teacherb\x06proto3"

var (
	file_teacher_proto_rawDescOnce sync.Once
	file_teacher_proto_rawDescData []byte
)

func file_teacher_proto_rawDescGZIP() []byte {
	file_teacher_proto_rawDescOnce.Do(func() {
		file_teacher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_teacher_proto_rawDesc), len(file_teacher_proto_rawDesc)))
	})
	return file_teacher_proto_rawDescData
}

var file_teacher_proto_msgTypes = make([]protoimpl.MessageInfo, 47)
var file_teacher_proto_goTypes = []any{
	(*CreateCourseRequest)(nil),          // 0: teacher.CreateCourseRequest
	(*CourseResponse)(nil),               // 1: teacher.CourseResponse
	(*AssignGradeRequest)(nil),           // 2: teacher.AssignGradeRequest
	(*GradeResponse)(nil),                // 3: teacher.GradeResponse
	(*GetStudentGradesRequest)(nil),      // 4: teacher.GetStudentGradesRequest
	(*GradeItem)(nil),                    // 5: teacher.GradeItem
	(*StudentGradesResponse)(nil),        // 6: teacher.StudentGradesResponse
	(*LoginTeacherRequest)(nil),          // 7: teacher.LoginTeacherRequest
	(*LoginTeacherResponse)(nil),         // 8: teacher.LoginTeacherResponse
	(*CreateTeacherRequest)(nil),         // 9: teacher.CreateTeacherRequest
	(*GetTeacherRequest)(nil),            // 10: teacher.GetTeacherRequest
	(*UpdateTeacherRequest)(nil),         // 11: teacher.UpdateTeacherRequest
	(*DeleteTeacherRequest)(nil),         // 12: teacher.DeleteTeacherRequest
	(*DeleteTeacherResponse)(nil),        // 13: teacher.DeleteTeacherResponse
	(*ListTeachersRequest)(nil),          // 14: teacher.ListTeachersRequest
	(*TeacherResponse)(nil),              // 15: teacher.TeacherResponse
	(*ListTeachersResponse)(nil),         // 16: teacher.ListTeachersResponse
	(*GetCoursesRequest)(nil),            // 17: teacher.GetCoursesRequest
	(*GetCoursesResponse)(nil),           // 18: teacher.GetCoursesResponse
	(*GetCourseRequest)(nil),             // 19: teacher.GetCourseRequest
	(*CourseDetailResponse)(nil),         // 20: teacher.CourseDetailResponse
	(*UpdateCourseRequest)(nil),          // 21: teacher.UpdateCourseRequest
	(*DeleteCourseRequest)(nil),          // 22: teacher.DeleteCourseRequest
	(*DeleteCourseResponse)(nil),         // 23: teacher.DeleteCourseResponse
	(*CreateAssignmentRequest)(nil),      // 24: teacher.CreateAssignmentRequest
	(*AssignmentResponse)(nil),           // 25: teacher.AssignmentResponse
	(*GetAssignmentRequest)(nil),         // 26: teacher.GetAssignmentRequest
	(*AssignmentDetailResponse)(nil),     // 27: teacher.AssignmentDetailResponse
	(*UpdateAssignmentRequest)(nil),      // 28: teacher.UpdateAssignmentRequest
	(*DeleteAssignmentRequest)(nil),      // 29: teacher.DeleteAssignmentRequest
	(*DeleteAssignmentResponse)(nil),     // 30: teacher.DeleteAssignmentResponse
	(*ListAssignmentsRequest)(nil),       // 31: teacher.ListAssignmentsRequest
	(*ListAssignmentsResponse)(nil),      // 32: teacher.ListAssignmentsResponse
	(*GetStudentCourseGradeRequest)(nil), // 33: teacher.GetStudentCourseGradeRequest
	(*AssignmentGradeItem)(nil),          // 34: teacher.AssignmentGradeItem
	(*StudentCourseGradeResponse)(nil),   // 35: teacher.StudentCourseGradeResponse
	(*EnrollStudentRequest)(nil),         // 36: teacher.EnrollStudentRequest
	(*EnrollmentResponse)(nil),           // 37: teacher.EnrollmentResponse
	(*GetCourseEnrollmentsRequest)(nil),  // 38: teacher.GetCourseEnrollmentsRequest
	(*EnrollmentItem)(nil),               // 39: teacher.EnrollmentItem
	(*GetCourseEnrollmentsResponse)(nil), // 40: teacher.GetCourseEnrollmentsResponse
	(*GetCourseGradesRequest)(nil),       // 41: teacher.GetCourseGradesRequest
	(*StudentGradeItem)(nil),             // 42: teacher.StudentGradeItem
	(*CourseGradesResponse)(nil),         // 43: teacher.CourseGradesResponse
	(*GetTeacherDashboardRequest)(nil),   // 44: teacher.GetTeacherDashboardRequest
	(*TeacherDashboardResponse)(nil),     // 45: teacher.TeacherDashboardResponse
	(*CourseSummary)(nil),                // 46: teacher.CourseSummary
}
var file_teacher_proto_depIdxs = []int32{
	5,  // 0: teacher.StudentGradesResponse.grades:type_name -> teacher.GradeItem
	15, // 1: teacher.ListTeachersResponse.teachers:type_name -> teacher.TeacherResponse
	20, // 2: teacher.GetCoursesResponse.courses:type_name -> teacher.CourseDetailResponse
	27, // 3: teacher.ListAssignmentsResponse.assignments:type_name -> teacher.AssignmentDetailResponse
	34, // 4: teacher.StudentCourseGradeResponse.assignments:type_name -> teacher.AssignmentGradeItem
	39, // 5: teacher.GetCourseEnrollmentsResponse.enrollments:type_name -> teacher.EnrollmentItem
	42, // 6: teacher.CourseGradesResponse.grades:type_name -> teacher.StudentGradeItem
	46, // 7: teacher.TeacherDashboardResponse.courses:type_name -> teacher.CourseSummary
	7,  // 8: teacher.TeacherService.LoginTeacher:input_type -> teacher.LoginTeacherRequest
	9,  // 9: teacher.TeacherService.CreateTeacher:input_type -> teacher.CreateTeacherRequest
	10, // 10: teacher.TeacherService.GetTeacher:input_type -> teacher.GetTeacherRequest
	11, // 11: teacher.TeacherService.UpdateTeacher:input_type -> teacher.UpdateTeacherRequest
	12, // 12: teacher.TeacherService.DeleteTeacher:input_type -> teacher.DeleteTeacherRequest
	14, // 13: teacher.TeacherService.ListTeachers:input_type -> teacher.ListTeachersRequest
	0,  // 14: teacher.TeacherService.CreateCourse:input_type -> teacher.CreateCourseRequest
	17, // 15: teacher.TeacherService.GetCourses:input_type -> teacher.GetCoursesRequest
	19, // 16: teacher.TeacherService.GetCourse:input_type -> teacher.GetCourseRequest
	21, // 17: teacher.TeacherService.UpdateCourse:input_type -> teacher.UpdateCourseRequest
	22, // 18: teacher.TeacherService.DeleteCourse:input_type -> teacher.DeleteCourseRequest
	24, // 19: teacher.TeacherService.CreateAssignment:input_type -> teacher.CreateAssignmentRequest
	26, // 20: teacher.TeacherService.GetAssignment:input_type -> teacher.GetAssignmentRequest
	28, // 21: teacher.TeacherService.UpdateAssignment:input_type -> teacher.UpdateAssignmentRequest
	29, // 22: teacher.TeacherService.DeleteAssignment:input_type -> teacher.DeleteAssignmentRequest
	31, // 23: teacher.TeacherService.ListAssignments:input_type -> teacher.ListAssignmentsRequest
	36, // 24: teacher.TeacherService.EnrollStudent:input_type -> teacher.EnrollStudentRequest
	38, // 25: teacher.TeacherService.GetCourseEnrollments:input_type -> teacher.GetCourseEnrollmentsRequest
	2,  // 26: teacher.TeacherService.AssignGrade:input_type -> teacher.AssignGradeRequest
	4,  // 27: teacher.TeacherService.GetStudentGrades:input_type -> teacher.GetStudentGradesRequest
	41, // 28: teacher.TeacherService.GetCourseGrades:input_type -> teacher.GetCourseGradesRequest
	33, // 29: teacher.TeacherService.GetStudentCourseGrade:input_type -> teacher.GetStudentCourseGradeRequest
	44, // 30: teacher.TeacherService.GetTeacherDashboard:input_type -> teacher.GetTeacherDashboardRequest
	8,  // 31: teacher.TeacherService.LoginTeacher:output_type -> teacher.LoginTeacherResponse
	15, // 32: teacher.TeacherService.CreateTeacher:output_type -> teacher.TeacherResponse
	15, // 33: teacher.TeacherService.GetTeacher:output_type -> teacher.TeacherResponse
	15, // 34: teacher.TeacherService.UpdateTeacher:output_type -> teacher.TeacherResponse
	13, // 35: teacher.TeacherService.DeleteTeacher:output_type -> teacher.DeleteTeacherResponse
	16, // 36: teacher.TeacherService.ListTeachers:output_type -> teacher.ListTeachersResponse
	1,  // 37: teacher.TeacherService.CreateCourse:output_type -> teacher.CourseResponse
	18, // 38: teacher.TeacherService.GetCourses:output_type -> teacher.GetCoursesResponse
	20, // 39: teacher.TeacherService.GetCourse:output_type -> teacher.CourseDetailResponse
	1,  // 40: teacher.TeacherService.UpdateCourse:output_type -> teacher.CourseResponse
	23, // 41: teacher.TeacherService.DeleteCourse:output_type -> teacher.DeleteCourseResponse
	25, // 42: teacher.TeacherService.CreateAssignment:output_type -> teacher.AssignmentResponse
	27, // 43: teacher.TeacherService.GetAssignment:output_type -> teacher.AssignmentDetailResponse
	25, // 44: teacher.TeacherService.UpdateAssignment:output_type -> teacher.AssignmentResponse
	30, // 45: teacher.TeacherService.DeleteAssignment:output_type -> teacher.DeleteAssignmentResponse
	32, // 46: teacher.TeacherService.ListAssignments:output_type -> teacher.ListAssignmentsResponse
	37, // 47: teacher.TeacherService.EnrollStudent:output_type -> teacher.EnrollmentResponse
	40, // 48: teacher.TeacherService.GetCourseEnrollments:output_type -> teacher.GetCourseEnrollmentsResponse
	3,  // 49: teacher.TeacherService.AssignGrade:output_type -> teacher.GradeResponse
	6,  // 50: teacher.TeacherService.GetStudentGrades:output_type -> teacher.StudentGradesResponse
	43, // 51: teacher.TeacherService.GetCourseGrades:output_type -> teacher.CourseGradesResponse
	35, // 52: teacher.TeacherService.GetStudentCourseGrade:output_type -> teacher.StudentCourseGradeResponse
	45, // 53: teacher.TeacherService.GetTeacherDashboard:output_type -> teacher.TeacherDashboardResponse
	31, // [31:54] is the sub-list for method output_type
	8,  // [8:31] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_teacher_proto_init() }
func file_teacher_proto_init() {
	if File_teacher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_teacher_proto_rawDesc), len(file_teacher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   47,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_teacher_proto_goTypes,
		DependencyIndexes: file_teacher_proto_depIdxs,
		MessageInfos:      file_teacher_proto_msgTypes,
	}.Build()
	File_teacher_proto = out.File
	file_teacher_proto_goTypes = nil
	file_teacher_proto_depIdxs = nil
}
