// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/teacher.proto

package teacher

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TeacherService_LoginTeacher_FullMethodName                 = "/teacher.TeacherService/LoginTeacher"
	TeacherService_CreateTeacher_FullMethodName                = "/teacher.TeacherService/CreateTeacher"
	TeacherService_GetTeacher_FullMethodName                   = "/teacher.TeacherService/GetTeacher"
	TeacherService_UpdateTeacher_FullMethodName                = "/teacher.TeacherService/UpdateTeacher"
	TeacherService_DeleteTeacher_FullMethodName                = "/teacher.TeacherService/DeleteTeacher"
	TeacherService_ListTeachers_FullMethodName                 = "/teacher.TeacherService/ListTeachers"
	TeacherService_CreateAssignment_FullMethodName             = "/teacher.TeacherService/CreateAssignment"
	TeacherService_GetAssignment_FullMethodName                = "/teacher.TeacherService/GetAssignment"
	TeacherService_UpdateAssignment_FullMethodName             = "/teacher.TeacherService/UpdateAssignment"
	TeacherService_DeleteAssignment_FullMethodName             = "/teacher.TeacherService/DeleteAssignment"
	TeacherService_ListAssignments_FullMethodName              = "/teacher.TeacherService/ListAssignments"
	TeacherService_GetTeacherCourseList_FullMethodName         = "/teacher.TeacherService/GetTeacherCourseList"
	TeacherService_AssignGrade_FullMethodName                  = "/teacher.TeacherService/AssignGrade"
	TeacherService_GetStudentGrades_FullMethodName             = "/teacher.TeacherService/GetStudentGrades"
	TeacherService_GetCourseGrades_FullMethodName              = "/teacher.TeacherService/GetCourseGrades"
	TeacherService_GetStudentCourseGrade_FullMethodName        = "/teacher.TeacherService/GetStudentCourseGrade"
	TeacherService_GetTeacherDashboard_FullMethodName          = "/teacher.TeacherService/GetTeacherDashboard"
	TeacherService_ValidateCourseHasAssignments_FullMethodName = "/teacher.TeacherService/ValidateCourseHasAssignments"
)

// TeacherServiceClient is the client API for TeacherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TeacherServiceClient interface {
	// Authentication
	LoginTeacher(ctx context.Context, in *LoginTeacherRequest, opts ...grpc.CallOption) (*LoginTeacherResponse, error)
	// Teacher CRUD
	CreateTeacher(ctx context.Context, in *CreateTeacherRequest, opts ...grpc.CallOption) (*TeacherResponse, error)
	GetTeacher(ctx context.Context, in *GetTeacherRequest, opts ...grpc.CallOption) (*TeacherResponse, error)
	UpdateTeacher(ctx context.Context, in *UpdateTeacherRequest, opts ...grpc.CallOption) (*TeacherResponse, error)
	DeleteTeacher(ctx context.Context, in *DeleteTeacherRequest, opts ...grpc.CallOption) (*DeleteTeacherResponse, error)
	ListTeachers(ctx context.Context, in *ListTeachersRequest, opts ...grpc.CallOption) (*ListTeachersResponse, error)
	// Assignment Management
	CreateAssignment(ctx context.Context, in *CreateAssignmentRequest, opts ...grpc.CallOption) (*AssignmentResponse, error)
	GetAssignment(ctx context.Context, in *GetAssignmentRequest, opts ...grpc.CallOption) (*AssignmentDetailResponse, error)
	UpdateAssignment(ctx context.Context, in *UpdateAssignmentRequest, opts ...grpc.CallOption) (*AssignmentResponse, error)
	DeleteAssignment(ctx context.Context, in *DeleteAssignmentRequest, opts ...grpc.CallOption) (*DeleteAssignmentResponse, error)
	ListAssignments(ctx context.Context, in *ListAssignmentsRequest, opts ...grpc.CallOption) (*ListAssignmentsResponse, error)
	GetTeacherCourseList(ctx context.Context, in *TeacherCourseListRequest, opts ...grpc.CallOption) (*TeacherCourseListResponse, error)
	// Grading
	AssignGrade(ctx context.Context, in *AssignGradeRequest, opts ...grpc.CallOption) (*GradeResponse, error)
	GetStudentGrades(ctx context.Context, in *GetStudentGradesRequest, opts ...grpc.CallOption) (*StudentGradesResponse, error)
	GetCourseGrades(ctx context.Context, in *GetCourseGradesRequest, opts ...grpc.CallOption) (*CourseGradesResponse, error)
	GetStudentCourseGrade(ctx context.Context, in *GetStudentCourseGradeRequest, opts ...grpc.CallOption) (*StudentCourseGradeResponse, error)
	// Reporting
	GetTeacherDashboard(ctx context.Context, in *GetTeacherDashboardRequest, opts ...grpc.CallOption) (*TeacherDashboardResponse, error)
	// Validation (used by School Service)
	ValidateCourseHasAssignments(ctx context.Context, in *ValidateCourseAssignmentsRequest, opts ...grpc.CallOption) (*ValidateCourseAssignmentsResponse, error)
}

type teacherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTeacherServiceClient(cc grpc.ClientConnInterface) TeacherServiceClient {
	return &teacherServiceClient{cc}
}

func (c *teacherServiceClient) LoginTeacher(ctx context.Context, in *LoginTeacherRequest, opts ...grpc.CallOption) (*LoginTeacherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginTeacherResponse)
	err := c.cc.Invoke(ctx, TeacherService_LoginTeacher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teacherServiceClient) CreateTeacher(ctx context.Context, in *CreateTeacherRequest, opts ...grpc.CallOption) (*TeacherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TeacherResponse)
	err := c.cc.Invoke(ctx, TeacherService_CreateTeacher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teacherServiceClient) GetTeacher(ctx context.Context, in *GetTeacherRequest, opts ...grpc.CallOption) (*TeacherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TeacherResponse)
	err := c.cc.Invoke(ctx, TeacherService_GetTeacher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teacherServiceClient) UpdateTeacher(ctx context.Context, in *UpdateTeacherRequest, opts ...grpc.CallOption) (*TeacherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TeacherResponse)
	err := c.cc.Invoke(ctx, TeacherService_UpdateTeacher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teacherServiceClient) DeleteTeacher(ctx context.Context, in *DeleteTeacherRequest, opts ...grpc.CallOption) (*DeleteTeacherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTeacherResponse)
	err := c.cc.Invoke(ctx, TeacherService_DeleteTeacher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teacherServiceClient) ListTeachers(ctx context.Context, in *ListTeachersRequest, opts ...grpc.CallOption) (*ListTeachersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTeachersResponse)
	err := c.cc.Invoke(ctx, TeacherService_ListTeachers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teacherServiceClient) CreateAssignment(ctx context.Context, in *CreateAssignmentRequest, opts ...grpc.CallOption) (*AssignmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignmentResponse)
	err := c.cc.Invoke(ctx, TeacherService_CreateAssignment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teacherServiceClient) GetAssignment(ctx context.Context, in *GetAssignmentRequest, opts ...grpc.CallOption) (*AssignmentDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignmentDetailResponse)
	err := c.cc.Invoke(ctx, TeacherService_GetAssignment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teacherServiceClient) UpdateAssignment(ctx context.Context, in *UpdateAssignmentRequest, opts ...grpc.CallOption) (*AssignmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignmentResponse)
	err := c.cc.Invoke(ctx, TeacherService_UpdateAssignment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teacherServiceClient) DeleteAssignment(ctx context.Context, in *DeleteAssignmentRequest, opts ...grpc.CallOption) (*DeleteAssignmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAssignmentResponse)
	err := c.cc.Invoke(ctx, TeacherService_DeleteAssignment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teacherServiceClient) ListAssignments(ctx context.Context, in *ListAssignmentsRequest, opts ...grpc.CallOption) (*ListAssignmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAssignmentsResponse)
	err := c.cc.Invoke(ctx, TeacherService_ListAssignments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teacherServiceClient) GetTeacherCourseList(ctx context.Context, in *TeacherCourseListRequest, opts ...grpc.CallOption) (*TeacherCourseListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TeacherCourseListResponse)
	err := c.cc.Invoke(ctx, TeacherService_GetTeacherCourseList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teacherServiceClient) AssignGrade(ctx context.Context, in *AssignGradeRequest, opts ...grpc.CallOption) (*GradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GradeResponse)
	err := c.cc.Invoke(ctx, TeacherService_AssignGrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teacherServiceClient) GetStudentGrades(ctx context.Context, in *GetStudentGradesRequest, opts ...grpc.CallOption) (*StudentGradesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudentGradesResponse)
	err := c.cc.Invoke(ctx, TeacherService_GetStudentGrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teacherServiceClient) GetCourseGrades(ctx context.Context, in *GetCourseGradesRequest, opts ...grpc.CallOption) (*CourseGradesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CourseGradesResponse)
	err := c.cc.Invoke(ctx, TeacherService_GetCourseGrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teacherServiceClient) GetStudentCourseGrade(ctx context.Context, in *GetStudentCourseGradeRequest, opts ...grpc.CallOption) (*StudentCourseGradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudentCourseGradeResponse)
	err := c.cc.Invoke(ctx, TeacherService_GetStudentCourseGrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teacherServiceClient) GetTeacherDashboard(ctx context.Context, in *GetTeacherDashboardRequest, opts ...grpc.CallOption) (*TeacherDashboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TeacherDashboardResponse)
	err := c.cc.Invoke(ctx, TeacherService_GetTeacherDashboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teacherServiceClient) ValidateCourseHasAssignments(ctx context.Context, in *ValidateCourseAssignmentsRequest, opts ...grpc.CallOption) (*ValidateCourseAssignmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateCourseAssignmentsResponse)
	err := c.cc.Invoke(ctx, TeacherService_ValidateCourseHasAssignments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeacherServiceServer is the server API for TeacherService service.
// All implementations must embed UnimplementedTeacherServiceServer
// for forward compatibility.
type TeacherServiceServer interface {
	// Authentication
	LoginTeacher(context.Context, *LoginTeacherRequest) (*LoginTeacherResponse, error)
	// Teacher CRUD
	CreateTeacher(context.Context, *CreateTeacherRequest) (*TeacherResponse, error)
	GetTeacher(context.Context, *GetTeacherRequest) (*TeacherResponse, error)
	UpdateTeacher(context.Context, *UpdateTeacherRequest) (*TeacherResponse, error)
	DeleteTeacher(context.Context, *DeleteTeacherRequest) (*DeleteTeacherResponse, error)
	ListTeachers(context.Context, *ListTeachersRequest) (*ListTeachersResponse, error)
	// Assignment Management
	CreateAssignment(context.Context, *CreateAssignmentRequest) (*AssignmentResponse, error)
	GetAssignment(context.Context, *GetAssignmentRequest) (*AssignmentDetailResponse, error)
	UpdateAssignment(context.Context, *UpdateAssignmentRequest) (*AssignmentResponse, error)
	DeleteAssignment(context.Context, *DeleteAssignmentRequest) (*DeleteAssignmentResponse, error)
	ListAssignments(context.Context, *ListAssignmentsRequest) (*ListAssignmentsResponse, error)
	GetTeacherCourseList(context.Context, *TeacherCourseListRequest) (*TeacherCourseListResponse, error)
	// Grading
	AssignGrade(context.Context, *AssignGradeRequest) (*GradeResponse, error)
	GetStudentGrades(context.Context, *GetStudentGradesRequest) (*StudentGradesResponse, error)
	GetCourseGrades(context.Context, *GetCourseGradesRequest) (*CourseGradesResponse, error)
	GetStudentCourseGrade(context.Context, *GetStudentCourseGradeRequest) (*StudentCourseGradeResponse, error)
	// Reporting
	GetTeacherDashboard(context.Context, *GetTeacherDashboardRequest) (*TeacherDashboardResponse, error)
	// Validation (used by School Service)
	ValidateCourseHasAssignments(context.Context, *ValidateCourseAssignmentsRequest) (*ValidateCourseAssignmentsResponse, error)
	mustEmbedUnimplementedTeacherServiceServer()
}

// UnimplementedTeacherServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTeacherServiceServer struct{}

func (UnimplementedTeacherServiceServer) LoginTeacher(context.Context, *LoginTeacherRequest) (*LoginTeacherResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginTeacher not implemented")
}
func (UnimplementedTeacherServiceServer) CreateTeacher(context.Context, *CreateTeacherRequest) (*TeacherResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTeacher not implemented")
}
func (UnimplementedTeacherServiceServer) GetTeacher(context.Context, *GetTeacherRequest) (*TeacherResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTeacher not implemented")
}
func (UnimplementedTeacherServiceServer) UpdateTeacher(context.Context, *UpdateTeacherRequest) (*TeacherResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTeacher not implemented")
}
func (UnimplementedTeacherServiceServer) DeleteTeacher(context.Context, *DeleteTeacherRequest) (*DeleteTeacherResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTeacher not implemented")
}
func (UnimplementedTeacherServiceServer) ListTeachers(context.Context, *ListTeachersRequest) (*ListTeachersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTeachers not implemented")
}
func (UnimplementedTeacherServiceServer) CreateAssignment(context.Context, *CreateAssignmentRequest) (*AssignmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAssignment not implemented")
}
func (UnimplementedTeacherServiceServer) GetAssignment(context.Context, *GetAssignmentRequest) (*AssignmentDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssignment not implemented")
}
func (UnimplementedTeacherServiceServer) UpdateAssignment(context.Context, *UpdateAssignmentRequest) (*AssignmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAssignment not implemented")
}
func (UnimplementedTeacherServiceServer) DeleteAssignment(context.Context, *DeleteAssignmentRequest) (*DeleteAssignmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAssignment not implemented")
}
func (UnimplementedTeacherServiceServer) ListAssignments(context.Context, *ListAssignmentsRequest) (*ListAssignmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAssignments not implemented")
}
func (UnimplementedTeacherServiceServer) GetTeacherCourseList(context.Context, *TeacherCourseListRequest) (*TeacherCourseListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTeacherCourseList not implemented")
}
func (UnimplementedTeacherServiceServer) AssignGrade(context.Context, *AssignGradeRequest) (*GradeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignGrade not implemented")
}
func (UnimplementedTeacherServiceServer) GetStudentGrades(context.Context, *GetStudentGradesRequest) (*StudentGradesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStudentGrades not implemented")
}
func (UnimplementedTeacherServiceServer) GetCourseGrades(context.Context, *GetCourseGradesRequest) (*CourseGradesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCourseGrades not implemented")
}
func (UnimplementedTeacherServiceServer) GetStudentCourseGrade(context.Context, *GetStudentCourseGradeRequest) (*StudentCourseGradeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStudentCourseGrade not implemented")
}
func (UnimplementedTeacherServiceServer) GetTeacherDashboard(context.Context, *GetTeacherDashboardRequest) (*TeacherDashboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTeacherDashboard not implemented")
}
func (UnimplementedTeacherServiceServer) ValidateCourseHasAssignments(context.Context, *ValidateCourseAssignmentsRequest) (*ValidateCourseAssignmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateCourseHasAssignments not implemented")
}
func (UnimplementedTeacherServiceServer) mustEmbedUnimplementedTeacherServiceServer() {}
func (UnimplementedTeacherServiceServer) testEmbeddedByValue()                        {}

// UnsafeTeacherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TeacherServiceServer will
// result in compilation errors.
type UnsafeTeacherServiceServer interface {
	mustEmbedUnimplementedTeacherServiceServer()
}

func RegisterTeacherServiceServer(s grpc.ServiceRegistrar, srv TeacherServiceServer) {
	// If the following call panics, it indicates UnimplementedTeacherServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TeacherService_ServiceDesc, srv)
}

func _TeacherService_LoginTeacher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginTeacherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherServiceServer).LoginTeacher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeacherService_LoginTeacher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherServiceServer).LoginTeacher(ctx, req.(*LoginTeacherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeacherService_CreateTeacher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTeacherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherServiceServer).CreateTeacher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeacherService_CreateTeacher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherServiceServer).CreateTeacher(ctx, req.(*CreateTeacherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeacherService_GetTeacher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeacherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherServiceServer).GetTeacher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeacherService_GetTeacher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherServiceServer).GetTeacher(ctx, req.(*GetTeacherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeacherService_UpdateTeacher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTeacherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherServiceServer).UpdateTeacher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeacherService_UpdateTeacher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherServiceServer).UpdateTeacher(ctx, req.(*UpdateTeacherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeacherService_DeleteTeacher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTeacherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherServiceServer).DeleteTeacher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeacherService_DeleteTeacher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherServiceServer).DeleteTeacher(ctx, req.(*DeleteTeacherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeacherService_ListTeachers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTeachersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherServiceServer).ListTeachers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeacherService_ListTeachers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherServiceServer).ListTeachers(ctx, req.(*ListTeachersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeacherService_CreateAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherServiceServer).CreateAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeacherService_CreateAssignment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherServiceServer).CreateAssignment(ctx, req.(*CreateAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeacherService_GetAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherServiceServer).GetAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeacherService_GetAssignment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherServiceServer).GetAssignment(ctx, req.(*GetAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeacherService_UpdateAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherServiceServer).UpdateAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeacherService_UpdateAssignment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherServiceServer).UpdateAssignment(ctx, req.(*UpdateAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeacherService_DeleteAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherServiceServer).DeleteAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeacherService_DeleteAssignment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherServiceServer).DeleteAssignment(ctx, req.(*DeleteAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeacherService_ListAssignments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAssignmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherServiceServer).ListAssignments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeacherService_ListAssignments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherServiceServer).ListAssignments(ctx, req.(*ListAssignmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeacherService_GetTeacherCourseList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeacherCourseListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherServiceServer).GetTeacherCourseList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeacherService_GetTeacherCourseList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherServiceServer).GetTeacherCourseList(ctx, req.(*TeacherCourseListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeacherService_AssignGrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignGradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherServiceServer).AssignGrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeacherService_AssignGrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherServiceServer).AssignGrade(ctx, req.(*AssignGradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeacherService_GetStudentGrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentGradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherServiceServer).GetStudentGrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeacherService_GetStudentGrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherServiceServer).GetStudentGrades(ctx, req.(*GetStudentGradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeacherService_GetCourseGrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseGradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherServiceServer).GetCourseGrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeacherService_GetCourseGrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherServiceServer).GetCourseGrades(ctx, req.(*GetCourseGradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeacherService_GetStudentCourseGrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentCourseGradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherServiceServer).GetStudentCourseGrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeacherService_GetStudentCourseGrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherServiceServer).GetStudentCourseGrade(ctx, req.(*GetStudentCourseGradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeacherService_GetTeacherDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeacherDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherServiceServer).GetTeacherDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeacherService_GetTeacherDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherServiceServer).GetTeacherDashboard(ctx, req.(*GetTeacherDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeacherService_ValidateCourseHasAssignments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateCourseAssignmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherServiceServer).ValidateCourseHasAssignments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeacherService_ValidateCourseHasAssignments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherServiceServer).ValidateCourseHasAssignments(ctx, req.(*ValidateCourseAssignmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TeacherService_ServiceDesc is the grpc.ServiceDesc for TeacherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TeacherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "teacher.TeacherService",
	HandlerType: (*TeacherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginTeacher",
			Handler:    _TeacherService_LoginTeacher_Handler,
		},
		{
			MethodName: "CreateTeacher",
			Handler:    _TeacherService_CreateTeacher_Handler,
		},
		{
			MethodName: "GetTeacher",
			Handler:    _TeacherService_GetTeacher_Handler,
		},
		{
			MethodName: "UpdateTeacher",
			Handler:    _TeacherService_UpdateTeacher_Handler,
		},
		{
			MethodName: "DeleteTeacher",
			Handler:    _TeacherService_DeleteTeacher_Handler,
		},
		{
			MethodName: "ListTeachers",
			Handler:    _TeacherService_ListTeachers_Handler,
		},
		{
			MethodName: "CreateAssignment",
			Handler:    _TeacherService_CreateAssignment_Handler,
		},
		{
			MethodName: "GetAssignment",
			Handler:    _TeacherService_GetAssignment_Handler,
		},
		{
			MethodName: "UpdateAssignment",
			Handler:    _TeacherService_UpdateAssignment_Handler,
		},
		{
			MethodName: "DeleteAssignment",
			Handler:    _TeacherService_DeleteAssignment_Handler,
		},
		{
			MethodName: "ListAssignments",
			Handler:    _TeacherService_ListAssignments_Handler,
		},
		{
			MethodName: "GetTeacherCourseList",
			Handler:    _TeacherService_GetTeacherCourseList_Handler,
		},
		{
			MethodName: "AssignGrade",
			Handler:    _TeacherService_AssignGrade_Handler,
		},
		{
			MethodName: "GetStudentGrades",
			Handler:    _TeacherService_GetStudentGrades_Handler,
		},
		{
			MethodName: "GetCourseGrades",
			Handler:    _TeacherService_GetCourseGrades_Handler,
		},
		{
			MethodName: "GetStudentCourseGrade",
			Handler:    _TeacherService_GetStudentCourseGrade_Handler,
		},
		{
			MethodName: "GetTeacherDashboard",
			Handler:    _TeacherService_GetTeacherDashboard_Handler,
		},
		{
			MethodName: "ValidateCourseHasAssignments",
			Handler:    _TeacherService_ValidateCourseHasAssignments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/teacher.proto",
}
