package main

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"log"
	"net"
	"os"
	"time"

	_ "github.com/lib/pq"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"

	pb "github.com/noxturnedev/lms-monorepo/proto/student"
	teacherpb "github.com/noxturnedev/lms-monorepo/proto/teacher"
	amqp "github.com/rabbitmq/amqp091-go"

	"go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"
	"google.golang.org/grpc/reflection"
)

// server controls the Student service logic
type server struct {
	pb.UnimplementedStudentServiceServer // Embedding for forward compatibility
	db                                   *sql.DB
	rabbitChannel                        *amqp.Channel
	teacherClient                        teacherpb.TeacherServiceClient
}

func (s *server) PublishEvent(event string, payload interface{}) error {
	body, err := json.Marshal(payload)
	if err != nil {
		return err
	}

	// We publish to the "student_events" queue
	err = s.rabbitChannel.Publish(
		"",               // exchange
		"student_events", // routing key (Queue Name)
		false,            // mandatory
		false,            // immediate
		amqp.Publishing{
			ContentType: "application/json",
			Body:        body,
			Type:        event, // e.g., "StudentDeleted"
		},
	)
	log.Printf("Published Event: %s", event)
	return err
}

// CreateStudent implements the gRPC method
func (s *server) CreateStudent(ctx context.Context, req *pb.CreateStudentRequest) (*pb.StudentResponse, error) {
	log.Printf("Received: CreateStudent for %v", req.Email)

	// Determine SQL query
	// Note: We use "RETURNING id" to get the UUID generated by Postgres
	query := `INSERT INTO students (email, full_name, password_hash, student_number) 
	          VALUES ($1, $2, $3, $4) RETURNING id`

	var id string
	err := s.db.QueryRow(query, req.Email, req.FullName, req.Password, req.StudentNumber).Scan(&id)
	if err != nil {
		return nil, fmt.Errorf("failed to insert student: %v", err)
	}

	return &pb.StudentResponse{
		Id:            id,
		Email:         req.Email,
		FullName:      req.FullName,
		StudentNumber: req.StudentNumber,
	}, nil
}

func (s *server) GetAllStudents(ctx context.Context, req *pb.ListStudentRequest) (*pb.ListStudentResponse, error) {
	log.Print("Received: GetAllStudent")

	query := "SELECT id, full_name, email, student_number FROM students"
	rows, err := s.db.QueryContext(ctx, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var students []*pb.StudentResponse

	for rows.Next() {
		var st pb.StudentResponse

		err := rows.Scan(
			&st.Id,
			&st.FullName,
			&st.Email,
			&st.StudentNumber,
		)
		if err != nil {
			return nil, err
		}

		students = append(students, &st)
	}

	if err = rows.Err(); err != nil {
		return nil, err
	}

	return &pb.ListStudentResponse{
		Students: students,
	}, nil
}

func (s *server) GetStudentById(ctx context.Context, req *pb.GetStudentByIdRequest) (*pb.StudentResponse, error) {
	log.Printf("Received: GetStudent for ID %v", req.Id)

	query := `SELECT id, email, full_name, student_number FROM students WHERE id = $1`

	var student pb.StudentResponse
	err := s.db.QueryRow(query, req.Id).Scan(&student.Id, &student.Email, &student.FullName, &student.StudentNumber)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("student not found")
		}
		return nil, err
	}

	return &student, nil
}

func (s *server) DeleteStudent(ctx context.Context, req *pb.DeleteStudentRequest) (*pb.DeleteStudentResponse, error) {
	log.Printf("Deleting Student: %v", req.Id)

	// 1. Delete from DB
	_, err := s.db.Exec("DELETE FROM students WHERE id = $1", req.Id)
	if err != nil {
		return nil, fmt.Errorf("failed to delete student: %v", err)
	}

	// 2. FIRE AND FORGET (Async Event)
	// We don't wait for the Teacher service. We just shout into the void.
	go func() {
		err := s.PublishEvent("StudentDeleted", map[string]string{"id": req.Id})
		if err != nil {
			log.Printf("Failed to publish event: %v", err)
		}
	}()

	return &pb.DeleteStudentResponse{Success: true}, nil
}

func (s *server) UpdateStudent(ctx context.Context, req *pb.UpdateStudentRequest) (*pb.StudentResponse, error) {
	log.Printf("Updating Student: %v", req.Id)

	if req.Password != "" {
		query := `UPDATE students SET email = $1, full_name = $2, student_number = $3, password_hash = $4
				WHERE id = $5 RETURNING id, email, full_name, student_number`
		var student pb.StudentResponse
		err := s.db.QueryRow(query, req.Email, req.FullName, req.StudentNumber, req.Password, req.Id).
			Scan(&student.Id, &student.Email, &student.FullName, &student.StudentNumber)
		if err != nil {
			return nil, fmt.Errorf("failed to update student: %v", err)
		}
		return &student, nil
	}

	query := `UPDATE students SET email = $1, full_name = $2, student_number = $3
			WHERE id = $4 RETURNING id, email, full_name, student_number`
	var student pb.StudentResponse
	err := s.db.QueryRow(query, req.Email, req.FullName, req.StudentNumber, req.Id).
		Scan(&student.Id, &student.Email, &student.FullName, &student.StudentNumber)
	if err != nil {
		return nil, fmt.Errorf("failed to update student: %v", err)
	}
	return &student, nil
}

func (s *server) GetStudentCourses(ctx context.Context, req *pb.GetStudentCoursesRequest) (*pb.GetStudentCoursesResponse, error) {
	log.Printf("Getting courses for student: %v", req.StudentId)

	_, err := s.db.Query("SELECT id FROM students WHERE id = $1", req.StudentId)
	if err != nil {
		return nil, fmt.Errorf("student not found")
	}

	coursesResp, err := s.teacherClient.GetCourses(ctx, &teacherpb.GetCoursesRequest{})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch courses: %v", err)
	}

	var studentCourses []*pb.CourseItem
	for _, course := range coursesResp.Courses {
		enrollments, err := s.teacherClient.GetCourseEnrollments(ctx, &teacherpb.GetCourseEnrollmentsRequest{
			CourseId: course.Id,
		})
		if err != nil {
			continue
		}

		for _, enrollment := range enrollments.Enrollments {
			if enrollment.StudentId == req.StudentId {
				studentCourses = append(studentCourses, &pb.CourseItem{
					CourseId:    course.Id,
					Title:       course.Title,
					Description: course.Description,
					TeacherName: course.TeacherName,
				})
				break
			}
		}
	}

	return &pb.GetStudentCoursesResponse{Courses: studentCourses}, nil
}

func main() {
	shutdown := initTracer()
	defer shutdown(context.Background())

	dbHost := os.Getenv("DATABASE_URL") // We set this in Docker Compose!
	if dbHost == "" {
		// Fallback for local testing (optional)
		dbHost = "postgres://student_admin:student_password@localhost:5434/student_db?sslmode=disable"
	}

	db, err := sql.Open("postgres", dbHost)
	if err != nil {
		log.Fatalf("failed to connect to db: %v", err)
	}
	defer db.Close()

	teacherServiceUrl := os.Getenv("TEACHER_SERVICE_URL")
	if teacherServiceUrl == "" {
		teacherServiceUrl = "localhost:8081"
	}

	teacherConn, err := grpc.NewClient(
		teacherServiceUrl,
		grpc.WithTransportCredentials(insecure.NewCredentials()),
		grpc.WithStatsHandler(otelgrpc.NewClientHandler()),
	)
	if err != nil {
		log.Fatalf("did not connect to teacher service: %v", err)
	}
	defer teacherConn.Close()

	teacherClient := teacherpb.NewTeacherServiceClient(teacherConn)

	lis, err := net.Listen("tcp", ":8080")
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}

	var rabbitConn *amqp.Connection
	var rabbitErr error

	for i := 0; i < 10; i++ {
		rabbitConn, rabbitErr = amqp.Dial("amqp://guest:guest@rabbitmq:5672/")
		if rabbitErr == nil {
			break
		}
		log.Println("Waiting for RabbitMQ...")
		time.Sleep(2 * time.Second)
	}
	if rabbitErr != nil {
		log.Fatalf("Failed to connect to RabbitMQ: %v", rabbitErr)
	}
	defer rabbitConn.Close()

	ch, err := rabbitConn.Channel()
	if err != nil {
		log.Fatalf("Failed to open channel: %v", err)
	}
	defer ch.Close()

	_, err = ch.QueueDeclare(
		"student_events", // name
		true,             // durable
		false,            // delete when unused
		false,            // exclusive
		false,            // no-wait
		nil,              // arguments
	)

	s := grpc.NewServer(
		grpc.StatsHandler(otelgrpc.NewServerHandler()),
	)
	pb.RegisterStudentServiceServer(s, &server{
		db:            db,
		rabbitChannel: ch,
		teacherClient: teacherClient,
	})

	reflection.Register(s)

	log.Println("Student Service listening on port 8080...")
	if err := s.Serve(lis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}
