// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/school.proto

package school

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Authentication Messages
type LoginAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginAdminRequest) Reset() {
	*x = LoginAdminRequest{}
	mi := &file_proto_school_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAdminRequest) ProtoMessage() {}

func (x *LoginAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_school_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginAdminRequest.ProtoReflect.Descriptor instead.
func (*LoginAdminRequest) Descriptor() ([]byte, []int) {
	return file_proto_school_proto_rawDescGZIP(), []int{0}
}

func (x *LoginAdminRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginAdminRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AdminId       string                 `protobuf:"bytes,3,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,5,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	SchoolId      string                 `protobuf:"bytes,6,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	SchoolName    string                 `protobuf:"bytes,7,opt,name=school_name,json=schoolName,proto3" json:"school_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginAdminResponse) Reset() {
	*x = LoginAdminResponse{}
	mi := &file_proto_school_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAdminResponse) ProtoMessage() {}

func (x *LoginAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_school_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginAdminResponse.ProtoReflect.Descriptor instead.
func (*LoginAdminResponse) Descriptor() ([]byte, []int) {
	return file_proto_school_proto_rawDescGZIP(), []int{1}
}

func (x *LoginAdminResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginAdminResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginAdminResponse) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *LoginAdminResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginAdminResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *LoginAdminResponse) GetSchoolId() string {
	if x != nil {
		return x.SchoolId
	}
	return ""
}

func (x *LoginAdminResponse) GetSchoolName() string {
	if x != nil {
		return x.SchoolName
	}
	return ""
}

// Admin CRUD Messages
type CreateAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	SchoolId      string                 `protobuf:"bytes,4,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdminRequest) Reset() {
	*x = CreateAdminRequest{}
	mi := &file_proto_school_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdminRequest) ProtoMessage() {}

func (x *CreateAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_school_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdminRequest.ProtoReflect.Descriptor instead.
func (*CreateAdminRequest) Descriptor() ([]byte, []int) {
	return file_proto_school_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAdminRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateAdminRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateAdminRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateAdminRequest) GetSchoolId() string {
	if x != nil {
		return x.SchoolId
	}
	return ""
}

type GetAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminRequest) Reset() {
	*x = GetAdminRequest{}
	mi := &file_proto_school_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminRequest) ProtoMessage() {}

func (x *GetAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_school_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminRequest.ProtoReflect.Descriptor instead.
func (*GetAdminRequest) Descriptor() ([]byte, []int) {
	return file_proto_school_proto_rawDescGZIP(), []int{3}
}

func (x *GetAdminRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"` // optional
	SchoolId      string                 `protobuf:"bytes,5,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdminRequest) Reset() {
	*x = UpdateAdminRequest{}
	mi := &file_proto_school_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdminRequest) ProtoMessage() {}

func (x *UpdateAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_school_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdminRequest.ProtoReflect.Descriptor instead.
func (*UpdateAdminRequest) Descriptor() ([]byte, []int) {
	return file_proto_school_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAdminRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAdminRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateAdminRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UpdateAdminRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateAdminRequest) GetSchoolId() string {
	if x != nil {
		return x.SchoolId
	}
	return ""
}

type DeleteAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdminRequest) Reset() {
	*x = DeleteAdminRequest{}
	mi := &file_proto_school_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdminRequest) ProtoMessage() {}

func (x *DeleteAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_school_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdminRequest.ProtoReflect.Descriptor instead.
func (*DeleteAdminRequest) Descriptor() ([]byte, []int) {
	return file_proto_school_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteAdminRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdminResponse) Reset() {
	*x = DeleteAdminResponse{}
	mi := &file_proto_school_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdminResponse) ProtoMessage() {}

func (x *DeleteAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_school_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdminResponse.ProtoReflect.Descriptor instead.
func (*DeleteAdminResponse) Descriptor() ([]byte, []int) {
	return file_proto_school_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAdminResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListAdminsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminsRequest) Reset() {
	*x = ListAdminsRequest{}
	mi := &file_proto_school_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminsRequest) ProtoMessage() {}

func (x *ListAdminsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_school_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminsRequest.ProtoReflect.Descriptor instead.
func (*ListAdminsRequest) Descriptor() ([]byte, []int) {
	return file_proto_school_proto_rawDescGZIP(), []int{7}
}

type AdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	SchoolId      string                 `protobuf:"bytes,4,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	SchoolName    string                 `protobuf:"bytes,5,opt,name=school_name,json=schoolName,proto3" json:"school_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminResponse) Reset() {
	*x = AdminResponse{}
	mi := &file_proto_school_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminResponse) ProtoMessage() {}

func (x *AdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_school_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminResponse.ProtoReflect.Descriptor instead.
func (*AdminResponse) Descriptor() ([]byte, []int) {
	return file_proto_school_proto_rawDescGZIP(), []int{8}
}

func (x *AdminResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdminResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *AdminResponse) GetSchoolId() string {
	if x != nil {
		return x.SchoolId
	}
	return ""
}

func (x *AdminResponse) GetSchoolName() string {
	if x != nil {
		return x.SchoolName
	}
	return ""
}

type ListAdminsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admins        []*AdminResponse       `protobuf:"bytes,1,rep,name=admins,proto3" json:"admins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminsResponse) Reset() {
	*x = ListAdminsResponse{}
	mi := &file_proto_school_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminsResponse) ProtoMessage() {}

func (x *ListAdminsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_school_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminsResponse.ProtoReflect.Descriptor instead.
func (*ListAdminsResponse) Descriptor() ([]byte, []int) {
	return file_proto_school_proto_rawDescGZIP(), []int{9}
}

func (x *ListAdminsResponse) GetAdmins() []*AdminResponse {
	if x != nil {
		return x.Admins
	}
	return nil
}

var File_proto_school_proto protoreflect.FileDescriptor

const file_proto_school_proto_rawDesc = "" +
	"\n" +
	"\x12proto/school.proto\x12\x06school\"E\n" +
	"\x11LoginAdminRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xd4\x01\n" +
	"\x12LoginAdminResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\badmin_id\x18\x03 \x01(\tR\aadminId\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x05 \x01(\tR\bfullName\x12\x1b\n" +
	"\tschool_id\x18\x06 \x01(\tR\bschoolId\x12\x1f\n" +
	"\vschool_name\x18\a \x01(\tR\n" +
	"schoolName\"\x80\x01\n" +
	"\x12CreateAdminRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x1b\n" +
	"\tschool_id\x18\x04 \x01(\tR\bschoolId\"!\n" +
	"\x0fGetAdminRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x90\x01\n" +
	"\x12UpdateAdminRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x1b\n" +
	"\tschool_id\x18\x05 \x01(\tR\bschoolId\"$\n" +
	"\x12DeleteAdminRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x13DeleteAdminResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x13\n" +
	"\x11ListAdminsRequest\"\x90\x01\n" +
	"\rAdminResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x1b\n" +
	"\tschool_id\x18\x04 \x01(\tR\bschoolId\x12\x1f\n" +
	"\vschool_name\x18\x05 \x01(\tR\n" +
	"schoolName\"C\n" +
	"\x12ListAdminsResponse\x12-\n" +
	"\x06admins\x18\x01 \x03(\v2\x15.school.AdminResponseR\x06admins2\xa1\x03\n" +
	"\rSchoolService\x12C\n" +
	"\n" +
	"LoginAdmin\x12\x19.school.LoginAdminRequest\x1a\x1a.school.LoginAdminResponse\x12@\n" +
	"\vCreateAdmin\x12\x1a.school.CreateAdminRequest\x1a\x15.school.AdminResponse\x12:\n" +
	"\bGetAdmin\x12\x17.school.GetAdminRequest\x1a\x15.school.AdminResponse\x12@\n" +
	"\vUpdateAdmin\x12\x1a.school.UpdateAdminRequest\x1a\x15.school.AdminResponse\x12F\n" +
	"\vDeleteAdmin\x12\x1a.school.DeleteAdminRequest\x1a\x1b.school.DeleteAdminResponse\x12C\n" +
	"\n" +
	"ListAdmins\x12\x19.school.ListAdminsRequest\x1a\x1a.school.ListAdminsResponseB2Z0github.com/noxturnedev/lms-monorepo/proto/schoolb\x06proto3"

var (
	file_proto_school_proto_rawDescOnce sync.Once
	file_proto_school_proto_rawDescData []byte
)

func file_proto_school_proto_rawDescGZIP() []byte {
	file_proto_school_proto_rawDescOnce.Do(func() {
		file_proto_school_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_school_proto_rawDesc), len(file_proto_school_proto_rawDesc)))
	})
	return file_proto_school_proto_rawDescData
}

var file_proto_school_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_school_proto_goTypes = []any{
	(*LoginAdminRequest)(nil),   // 0: school.LoginAdminRequest
	(*LoginAdminResponse)(nil),  // 1: school.LoginAdminResponse
	(*CreateAdminRequest)(nil),  // 2: school.CreateAdminRequest
	(*GetAdminRequest)(nil),     // 3: school.GetAdminRequest
	(*UpdateAdminRequest)(nil),  // 4: school.UpdateAdminRequest
	(*DeleteAdminRequest)(nil),  // 5: school.DeleteAdminRequest
	(*DeleteAdminResponse)(nil), // 6: school.DeleteAdminResponse
	(*ListAdminsRequest)(nil),   // 7: school.ListAdminsRequest
	(*AdminResponse)(nil),       // 8: school.AdminResponse
	(*ListAdminsResponse)(nil),  // 9: school.ListAdminsResponse
}
var file_proto_school_proto_depIdxs = []int32{
	8, // 0: school.ListAdminsResponse.admins:type_name -> school.AdminResponse
	0, // 1: school.SchoolService.LoginAdmin:input_type -> school.LoginAdminRequest
	2, // 2: school.SchoolService.CreateAdmin:input_type -> school.CreateAdminRequest
	3, // 3: school.SchoolService.GetAdmin:input_type -> school.GetAdminRequest
	4, // 4: school.SchoolService.UpdateAdmin:input_type -> school.UpdateAdminRequest
	5, // 5: school.SchoolService.DeleteAdmin:input_type -> school.DeleteAdminRequest
	7, // 6: school.SchoolService.ListAdmins:input_type -> school.ListAdminsRequest
	1, // 7: school.SchoolService.LoginAdmin:output_type -> school.LoginAdminResponse
	8, // 8: school.SchoolService.CreateAdmin:output_type -> school.AdminResponse
	8, // 9: school.SchoolService.GetAdmin:output_type -> school.AdminResponse
	8, // 10: school.SchoolService.UpdateAdmin:output_type -> school.AdminResponse
	6, // 11: school.SchoolService.DeleteAdmin:output_type -> school.DeleteAdminResponse
	9, // 12: school.SchoolService.ListAdmins:output_type -> school.ListAdminsResponse
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_school_proto_init() }
func file_proto_school_proto_init() {
	if File_proto_school_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_school_proto_rawDesc), len(file_proto_school_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_school_proto_goTypes,
		DependencyIndexes: file_proto_school_proto_depIdxs,
		MessageInfos:      file_proto_school_proto_msgTypes,
	}.Build()
	File_proto_school_proto = out.File
	file_proto_school_proto_goTypes = nil
	file_proto_school_proto_depIdxs = nil
}
