// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/teacher.proto

package teacher

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeacherId     string                 `protobuf:"bytes,1,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseRequest) Reset() {
	*x = CreateCourseRequest{}
	mi := &file_proto_teacher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseRequest) ProtoMessage() {}

func (x *CreateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseRequest.ProtoReflect.Descriptor instead.
func (*CreateCourseRequest) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCourseRequest) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *CreateCourseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCourseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseResponse) Reset() {
	*x = CourseResponse{}
	mi := &file_proto_teacher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseResponse) ProtoMessage() {}

func (x *CourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseResponse.ProtoReflect.Descriptor instead.
func (*CourseResponse) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{1}
}

func (x *CourseResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CourseResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type AssignGradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeacherId     string                 `protobuf:"bytes,1,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"` // Security check
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,3,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"` // The UUID from Student Service
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignGradeRequest) Reset() {
	*x = AssignGradeRequest{}
	mi := &file_proto_teacher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignGradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignGradeRequest) ProtoMessage() {}

func (x *AssignGradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignGradeRequest.ProtoReflect.Descriptor instead.
func (*AssignGradeRequest) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{2}
}

func (x *AssignGradeRequest) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *AssignGradeRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *AssignGradeRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *AssignGradeRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type GradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeResponse) Reset() {
	*x = GradeResponse{}
	mi := &file_proto_teacher_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeResponse) ProtoMessage() {}

func (x *GradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeResponse.ProtoReflect.Descriptor instead.
func (*GradeResponse) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{3}
}

func (x *GradeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GradeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetStudentGradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentGradesRequest) Reset() {
	*x = GetStudentGradesRequest{}
	mi := &file_proto_teacher_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentGradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentGradesRequest) ProtoMessage() {}

func (x *GetStudentGradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentGradesRequest.ProtoReflect.Descriptor instead.
func (*GetStudentGradesRequest) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{4}
}

func (x *GetStudentGradesRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type GradeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseTitle   string                 `protobuf:"bytes,1,opt,name=course_title,json=courseTitle,proto3" json:"course_title,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeItem) Reset() {
	*x = GradeItem{}
	mi := &file_proto_teacher_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeItem) ProtoMessage() {}

func (x *GradeItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeItem.ProtoReflect.Descriptor instead.
func (*GradeItem) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{5}
}

func (x *GradeItem) GetCourseTitle() string {
	if x != nil {
		return x.CourseTitle
	}
	return ""
}

func (x *GradeItem) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type StudentGradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grades        []*GradeItem           `protobuf:"bytes,1,rep,name=grades,proto3" json:"grades,omitempty"` // array in proto
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentGradesResponse) Reset() {
	*x = StudentGradesResponse{}
	mi := &file_proto_teacher_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentGradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentGradesResponse) ProtoMessage() {}

func (x *StudentGradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentGradesResponse.ProtoReflect.Descriptor instead.
func (*StudentGradesResponse) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{6}
}

func (x *StudentGradesResponse) GetGrades() []*GradeItem {
	if x != nil {
		return x.Grades
	}
	return nil
}

// Teacher CRUD Messages
type CreateTeacherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeacherRequest) Reset() {
	*x = CreateTeacherRequest{}
	mi := &file_proto_teacher_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeacherRequest) ProtoMessage() {}

func (x *CreateTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeacherRequest.ProtoReflect.Descriptor instead.
func (*CreateTeacherRequest) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTeacherRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateTeacherRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateTeacherRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

type GetTeacherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeacherRequest) Reset() {
	*x = GetTeacherRequest{}
	mi := &file_proto_teacher_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeacherRequest) ProtoMessage() {}

func (x *GetTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeacherRequest.ProtoReflect.Descriptor instead.
func (*GetTeacherRequest) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{8}
}

func (x *GetTeacherRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateTeacherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeacherRequest) Reset() {
	*x = UpdateTeacherRequest{}
	mi := &file_proto_teacher_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeacherRequest) ProtoMessage() {}

func (x *UpdateTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeacherRequest.ProtoReflect.Descriptor instead.
func (*UpdateTeacherRequest) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTeacherRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTeacherRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateTeacherRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UpdateTeacherRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type DeleteTeacherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeacherRequest) Reset() {
	*x = DeleteTeacherRequest{}
	mi := &file_proto_teacher_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeacherRequest) ProtoMessage() {}

func (x *DeleteTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeacherRequest.ProtoReflect.Descriptor instead.
func (*DeleteTeacherRequest) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTeacherRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTeacherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeacherResponse) Reset() {
	*x = DeleteTeacherResponse{}
	mi := &file_proto_teacher_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeacherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeacherResponse) ProtoMessage() {}

func (x *DeleteTeacherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeacherResponse.ProtoReflect.Descriptor instead.
func (*DeleteTeacherResponse) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteTeacherResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListTeachersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeachersRequest) Reset() {
	*x = ListTeachersRequest{}
	mi := &file_proto_teacher_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeachersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeachersRequest) ProtoMessage() {}

func (x *ListTeachersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeachersRequest.ProtoReflect.Descriptor instead.
func (*ListTeachersRequest) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{12}
}

type TeacherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeacherResponse) Reset() {
	*x = TeacherResponse{}
	mi := &file_proto_teacher_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeacherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeacherResponse) ProtoMessage() {}

func (x *TeacherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeacherResponse.ProtoReflect.Descriptor instead.
func (*TeacherResponse) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{13}
}

func (x *TeacherResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TeacherResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TeacherResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

type ListTeachersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teachers      []*TeacherResponse     `protobuf:"bytes,1,rep,name=teachers,proto3" json:"teachers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeachersResponse) Reset() {
	*x = ListTeachersResponse{}
	mi := &file_proto_teacher_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeachersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeachersResponse) ProtoMessage() {}

func (x *ListTeachersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeachersResponse.ProtoReflect.Descriptor instead.
func (*ListTeachersResponse) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{14}
}

func (x *ListTeachersResponse) GetTeachers() []*TeacherResponse {
	if x != nil {
		return x.Teachers
	}
	return nil
}

// Course Management Messages
type GetCoursesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeacherId     string                 `protobuf:"bytes,1,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoursesRequest) Reset() {
	*x = GetCoursesRequest{}
	mi := &file_proto_teacher_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoursesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesRequest) ProtoMessage() {}

func (x *GetCoursesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesRequest.ProtoReflect.Descriptor instead.
func (*GetCoursesRequest) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{15}
}

func (x *GetCoursesRequest) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

type GetCoursesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Courses       []*CourseDetailResponse `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoursesResponse) Reset() {
	*x = GetCoursesResponse{}
	mi := &file_proto_teacher_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoursesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesResponse) ProtoMessage() {}

func (x *GetCoursesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesResponse.ProtoReflect.Descriptor instead.
func (*GetCoursesResponse) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{16}
}

func (x *GetCoursesResponse) GetCourses() []*CourseDetailResponse {
	if x != nil {
		return x.Courses
	}
	return nil
}

type GetCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseRequest) Reset() {
	*x = GetCourseRequest{}
	mi := &file_proto_teacher_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseRequest) ProtoMessage() {}

func (x *GetCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseRequest.ProtoReflect.Descriptor instead.
func (*GetCourseRequest) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{17}
}

func (x *GetCourseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CourseDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TeacherId     string                 `protobuf:"bytes,2,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	TeacherName   string                 `protobuf:"bytes,5,opt,name=teacher_name,json=teacherName,proto3" json:"teacher_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseDetailResponse) Reset() {
	*x = CourseDetailResponse{}
	mi := &file_proto_teacher_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseDetailResponse) ProtoMessage() {}

func (x *CourseDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseDetailResponse.ProtoReflect.Descriptor instead.
func (*CourseDetailResponse) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{18}
}

func (x *CourseDetailResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CourseDetailResponse) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *CourseDetailResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CourseDetailResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CourseDetailResponse) GetTeacherName() string {
	if x != nil {
		return x.TeacherName
	}
	return ""
}

type UpdateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseRequest) Reset() {
	*x = UpdateCourseRequest{}
	mi := &file_proto_teacher_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseRequest) ProtoMessage() {}

func (x *UpdateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseRequest.ProtoReflect.Descriptor instead.
func (*UpdateCourseRequest) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateCourseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCourseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateCourseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeleteCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseRequest) Reset() {
	*x = DeleteCourseRequest{}
	mi := &file_proto_teacher_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseRequest) ProtoMessage() {}

func (x *DeleteCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseRequest.ProtoReflect.Descriptor instead.
func (*DeleteCourseRequest) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteCourseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseResponse) Reset() {
	*x = DeleteCourseResponse{}
	mi := &file_proto_teacher_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseResponse) ProtoMessage() {}

func (x *DeleteCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseResponse.ProtoReflect.Descriptor instead.
func (*DeleteCourseResponse) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteCourseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteCourseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Enrollment Messages
type EnrollStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollStudentRequest) Reset() {
	*x = EnrollStudentRequest{}
	mi := &file_proto_teacher_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollStudentRequest) ProtoMessage() {}

func (x *EnrollStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollStudentRequest.ProtoReflect.Descriptor instead.
func (*EnrollStudentRequest) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{22}
}

func (x *EnrollStudentRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *EnrollStudentRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type EnrollmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollmentResponse) Reset() {
	*x = EnrollmentResponse{}
	mi := &file_proto_teacher_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentResponse) ProtoMessage() {}

func (x *EnrollmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentResponse.ProtoReflect.Descriptor instead.
func (*EnrollmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{23}
}

func (x *EnrollmentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EnrollmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnrollmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetCourseEnrollmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseEnrollmentsRequest) Reset() {
	*x = GetCourseEnrollmentsRequest{}
	mi := &file_proto_teacher_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseEnrollmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseEnrollmentsRequest) ProtoMessage() {}

func (x *GetCourseEnrollmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseEnrollmentsRequest.ProtoReflect.Descriptor instead.
func (*GetCourseEnrollmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{24}
}

func (x *GetCourseEnrollmentsRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type EnrollmentItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StudentName   string                 `protobuf:"bytes,2,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	StudentNumber string                 `protobuf:"bytes,3,opt,name=student_number,json=studentNumber,proto3" json:"student_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollmentItem) Reset() {
	*x = EnrollmentItem{}
	mi := &file_proto_teacher_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentItem) ProtoMessage() {}

func (x *EnrollmentItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentItem.ProtoReflect.Descriptor instead.
func (*EnrollmentItem) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{25}
}

func (x *EnrollmentItem) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *EnrollmentItem) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *EnrollmentItem) GetStudentNumber() string {
	if x != nil {
		return x.StudentNumber
	}
	return ""
}

type GetCourseEnrollmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enrollments   []*EnrollmentItem      `protobuf:"bytes,1,rep,name=enrollments,proto3" json:"enrollments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseEnrollmentsResponse) Reset() {
	*x = GetCourseEnrollmentsResponse{}
	mi := &file_proto_teacher_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseEnrollmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseEnrollmentsResponse) ProtoMessage() {}

func (x *GetCourseEnrollmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseEnrollmentsResponse.ProtoReflect.Descriptor instead.
func (*GetCourseEnrollmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{26}
}

func (x *GetCourseEnrollmentsResponse) GetEnrollments() []*EnrollmentItem {
	if x != nil {
		return x.Enrollments
	}
	return nil
}

// Gradebook Messages
type GetCourseGradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseGradesRequest) Reset() {
	*x = GetCourseGradesRequest{}
	mi := &file_proto_teacher_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseGradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseGradesRequest) ProtoMessage() {}

func (x *GetCourseGradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseGradesRequest.ProtoReflect.Descriptor instead.
func (*GetCourseGradesRequest) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{27}
}

func (x *GetCourseGradesRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type StudentGradeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StudentName   string                 `protobuf:"bytes,2,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	StudentNumber string                 `protobuf:"bytes,3,opt,name=student_number,json=studentNumber,proto3" json:"student_number,omitempty"`
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	GradeId       string                 `protobuf:"bytes,5,opt,name=grade_id,json=gradeId,proto3" json:"grade_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentGradeItem) Reset() {
	*x = StudentGradeItem{}
	mi := &file_proto_teacher_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentGradeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentGradeItem) ProtoMessage() {}

func (x *StudentGradeItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentGradeItem.ProtoReflect.Descriptor instead.
func (*StudentGradeItem) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{28}
}

func (x *StudentGradeItem) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *StudentGradeItem) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *StudentGradeItem) GetStudentNumber() string {
	if x != nil {
		return x.StudentNumber
	}
	return ""
}

func (x *StudentGradeItem) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *StudentGradeItem) GetGradeId() string {
	if x != nil {
		return x.GradeId
	}
	return ""
}

type CourseGradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	CourseTitle   string                 `protobuf:"bytes,2,opt,name=course_title,json=courseTitle,proto3" json:"course_title,omitempty"`
	Grades        []*StudentGradeItem    `protobuf:"bytes,3,rep,name=grades,proto3" json:"grades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseGradesResponse) Reset() {
	*x = CourseGradesResponse{}
	mi := &file_proto_teacher_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseGradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseGradesResponse) ProtoMessage() {}

func (x *CourseGradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseGradesResponse.ProtoReflect.Descriptor instead.
func (*CourseGradesResponse) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{29}
}

func (x *CourseGradesResponse) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CourseGradesResponse) GetCourseTitle() string {
	if x != nil {
		return x.CourseTitle
	}
	return ""
}

func (x *CourseGradesResponse) GetGrades() []*StudentGradeItem {
	if x != nil {
		return x.Grades
	}
	return nil
}

// Dashboard Messages
type GetTeacherDashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeacherId     string                 `protobuf:"bytes,1,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeacherDashboardRequest) Reset() {
	*x = GetTeacherDashboardRequest{}
	mi := &file_proto_teacher_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeacherDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeacherDashboardRequest) ProtoMessage() {}

func (x *GetTeacherDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeacherDashboardRequest.ProtoReflect.Descriptor instead.
func (*GetTeacherDashboardRequest) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{30}
}

func (x *GetTeacherDashboardRequest) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

type TeacherDashboardResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TeacherId             string                 `protobuf:"bytes,1,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	TeacherName           string                 `protobuf:"bytes,2,opt,name=teacher_name,json=teacherName,proto3" json:"teacher_name,omitempty"`
	TotalCourses          int32                  `protobuf:"varint,3,opt,name=total_courses,json=totalCourses,proto3" json:"total_courses,omitempty"`
	TotalStudentsEnrolled int32                  `protobuf:"varint,4,opt,name=total_students_enrolled,json=totalStudentsEnrolled,proto3" json:"total_students_enrolled,omitempty"`
	Courses               []*CourseSummary       `protobuf:"bytes,5,rep,name=courses,proto3" json:"courses,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TeacherDashboardResponse) Reset() {
	*x = TeacherDashboardResponse{}
	mi := &file_proto_teacher_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeacherDashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeacherDashboardResponse) ProtoMessage() {}

func (x *TeacherDashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeacherDashboardResponse.ProtoReflect.Descriptor instead.
func (*TeacherDashboardResponse) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{31}
}

func (x *TeacherDashboardResponse) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *TeacherDashboardResponse) GetTeacherName() string {
	if x != nil {
		return x.TeacherName
	}
	return ""
}

func (x *TeacherDashboardResponse) GetTotalCourses() int32 {
	if x != nil {
		return x.TotalCourses
	}
	return 0
}

func (x *TeacherDashboardResponse) GetTotalStudentsEnrolled() int32 {
	if x != nil {
		return x.TotalStudentsEnrolled
	}
	return 0
}

func (x *TeacherDashboardResponse) GetCourses() []*CourseSummary {
	if x != nil {
		return x.Courses
	}
	return nil
}

type CourseSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	EnrolledCount int32                  `protobuf:"varint,3,opt,name=enrolled_count,json=enrolledCount,proto3" json:"enrolled_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseSummary) Reset() {
	*x = CourseSummary{}
	mi := &file_proto_teacher_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseSummary) ProtoMessage() {}

func (x *CourseSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teacher_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseSummary.ProtoReflect.Descriptor instead.
func (*CourseSummary) Descriptor() ([]byte, []int) {
	return file_proto_teacher_proto_rawDescGZIP(), []int{32}
}

func (x *CourseSummary) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CourseSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CourseSummary) GetEnrolledCount() int32 {
	if x != nil {
		return x.EnrolledCount
	}
	return 0
}

var File_proto_teacher_proto protoreflect.FileDescriptor

const file_proto_teacher_proto_rawDesc = "" +
	"\n" +
	"\x13proto/teacher.proto\x12\ateacher\"l\n" +
	"\x13CreateCourseRequest\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x01 \x01(\tR\tteacherId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"6\n" +
	"\x0eCourseResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"\x85\x01\n" +
	"\x12AssignGradeRequest\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x01 \x01(\tR\tteacherId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x03 \x01(\tR\tstudentId\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\"9\n" +
	"\rGradeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"8\n" +
	"\x17GetStudentGradesRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\"D\n" +
	"\tGradeItem\x12!\n" +
	"\fcourse_title\x18\x01 \x01(\tR\vcourseTitle\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\"C\n" +
	"\x15StudentGradesResponse\x12*\n" +
	"\x06grades\x18\x01 \x03(\v2\x12.teacher.GradeItemR\x06grades\"e\n" +
	"\x14CreateTeacherRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\"#\n" +
	"\x11GetTeacherRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"u\n" +
	"\x14UpdateTeacherRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"&\n" +
	"\x14DeleteTeacherRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteTeacherResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x15\n" +
	"\x13ListTeachersRequest\"T\n" +
	"\x0fTeacherResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\"L\n" +
	"\x14ListTeachersResponse\x124\n" +
	"\bteachers\x18\x01 \x03(\v2\x18.teacher.TeacherResponseR\bteachers\"2\n" +
	"\x11GetCoursesRequest\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x01 \x01(\tR\tteacherId\"M\n" +
	"\x12GetCoursesResponse\x127\n" +
	"\acourses\x18\x01 \x03(\v2\x1d.teacher.CourseDetailResponseR\acourses\"\"\n" +
	"\x10GetCourseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa0\x01\n" +
	"\x14CourseDetailResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x02 \x01(\tR\tteacherId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12!\n" +
	"\fteacher_name\x18\x05 \x01(\tR\vteacherName\"]\n" +
	"\x13UpdateCourseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"%\n" +
	"\x13DeleteCourseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x14DeleteCourseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"R\n" +
	"\x14EnrollStudentRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"X\n" +
	"\x12EnrollmentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\":\n" +
	"\x1bGetCourseEnrollmentsRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"y\n" +
	"\x0eEnrollmentItem\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12!\n" +
	"\fstudent_name\x18\x02 \x01(\tR\vstudentName\x12%\n" +
	"\x0estudent_number\x18\x03 \x01(\tR\rstudentNumber\"Y\n" +
	"\x1cGetCourseEnrollmentsResponse\x129\n" +
	"\venrollments\x18\x01 \x03(\v2\x17.teacher.EnrollmentItemR\venrollments\"5\n" +
	"\x16GetCourseGradesRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"\xac\x01\n" +
	"\x10StudentGradeItem\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12!\n" +
	"\fstudent_name\x18\x02 \x01(\tR\vstudentName\x12%\n" +
	"\x0estudent_number\x18\x03 \x01(\tR\rstudentNumber\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x12\x19\n" +
	"\bgrade_id\x18\x05 \x01(\tR\agradeId\"\x89\x01\n" +
	"\x14CourseGradesResponse\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12!\n" +
	"\fcourse_title\x18\x02 \x01(\tR\vcourseTitle\x121\n" +
	"\x06grades\x18\x03 \x03(\v2\x19.teacher.StudentGradeItemR\x06grades\";\n" +
	"\x1aGetTeacherDashboardRequest\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x01 \x01(\tR\tteacherId\"\xeb\x01\n" +
	"\x18TeacherDashboardResponse\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x01 \x01(\tR\tteacherId\x12!\n" +
	"\fteacher_name\x18\x02 \x01(\tR\vteacherName\x12#\n" +
	"\rtotal_courses\x18\x03 \x01(\x05R\ftotalCourses\x126\n" +
	"\x17total_students_enrolled\x18\x04 \x01(\x05R\x15totalStudentsEnrolled\x120\n" +
	"\acourses\x18\x05 \x03(\v2\x16.teacher.CourseSummaryR\acourses\"i\n" +
	"\rCourseSummary\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\x0eenrolled_count\x18\x03 \x01(\x05R\renrolledCount2\xec\t\n" +
	"\x0eTeacherService\x12H\n" +
	"\rCreateTeacher\x12\x1d.teacher.CreateTeacherRequest\x1a\x18.teacher.TeacherResponse\x12B\n" +
	"\n" +
	"GetTeacher\x12\x1a.teacher.GetTeacherRequest\x1a\x18.teacher.TeacherResponse\x12H\n" +
	"\rUpdateTeacher\x12\x1d.teacher.UpdateTeacherRequest\x1a\x18.teacher.TeacherResponse\x12N\n" +
	"\rDeleteTeacher\x12\x1d.teacher.DeleteTeacherRequest\x1a\x1e.teacher.DeleteTeacherResponse\x12K\n" +
	"\fListTeachers\x12\x1c.teacher.ListTeachersRequest\x1a\x1d.teacher.ListTeachersResponse\x12E\n" +
	"\fCreateCourse\x12\x1c.teacher.CreateCourseRequest\x1a\x17.teacher.CourseResponse\x12E\n" +
	"\n" +
	"GetCourses\x12\x1a.teacher.GetCoursesRequest\x1a\x1b.teacher.GetCoursesResponse\x12E\n" +
	"\tGetCourse\x12\x19.teacher.GetCourseRequest\x1a\x1d.teacher.CourseDetailResponse\x12E\n" +
	"\fUpdateCourse\x12\x1c.teacher.UpdateCourseRequest\x1a\x17.teacher.CourseResponse\x12K\n" +
	"\fDeleteCourse\x12\x1c.teacher.DeleteCourseRequest\x1a\x1d.teacher.DeleteCourseResponse\x12K\n" +
	"\rEnrollStudent\x12\x1d.teacher.EnrollStudentRequest\x1a\x1b.teacher.EnrollmentResponse\x12c\n" +
	"\x14GetCourseEnrollments\x12$.teacher.GetCourseEnrollmentsRequest\x1a%.teacher.GetCourseEnrollmentsResponse\x12B\n" +
	"\vAssignGrade\x12\x1b.teacher.AssignGradeRequest\x1a\x16.teacher.GradeResponse\x12T\n" +
	"\x10GetStudentGrades\x12 .teacher.GetStudentGradesRequest\x1a\x1e.teacher.StudentGradesResponse\x12Q\n" +
	"\x0fGetCourseGrades\x12\x1f.teacher.GetCourseGradesRequest\x1a\x1d.teacher.CourseGradesResponse\x12]\n" +
	"\x13GetTeacherDashboard\x12#.teacher.GetTeacherDashboardRequest\x1a!.teacher.TeacherDashboardResponseBCZAgithub.com/noxturnedev/lms-monorepo/teacher-service/proto/teacherb\x06proto3"

var (
	file_proto_teacher_proto_rawDescOnce sync.Once
	file_proto_teacher_proto_rawDescData []byte
)

func file_proto_teacher_proto_rawDescGZIP() []byte {
	file_proto_teacher_proto_rawDescOnce.Do(func() {
		file_proto_teacher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_teacher_proto_rawDesc), len(file_proto_teacher_proto_rawDesc)))
	})
	return file_proto_teacher_proto_rawDescData
}

var file_proto_teacher_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_proto_teacher_proto_goTypes = []any{
	(*CreateCourseRequest)(nil),          // 0: teacher.CreateCourseRequest
	(*CourseResponse)(nil),               // 1: teacher.CourseResponse
	(*AssignGradeRequest)(nil),           // 2: teacher.AssignGradeRequest
	(*GradeResponse)(nil),                // 3: teacher.GradeResponse
	(*GetStudentGradesRequest)(nil),      // 4: teacher.GetStudentGradesRequest
	(*GradeItem)(nil),                    // 5: teacher.GradeItem
	(*StudentGradesResponse)(nil),        // 6: teacher.StudentGradesResponse
	(*CreateTeacherRequest)(nil),         // 7: teacher.CreateTeacherRequest
	(*GetTeacherRequest)(nil),            // 8: teacher.GetTeacherRequest
	(*UpdateTeacherRequest)(nil),         // 9: teacher.UpdateTeacherRequest
	(*DeleteTeacherRequest)(nil),         // 10: teacher.DeleteTeacherRequest
	(*DeleteTeacherResponse)(nil),        // 11: teacher.DeleteTeacherResponse
	(*ListTeachersRequest)(nil),          // 12: teacher.ListTeachersRequest
	(*TeacherResponse)(nil),              // 13: teacher.TeacherResponse
	(*ListTeachersResponse)(nil),         // 14: teacher.ListTeachersResponse
	(*GetCoursesRequest)(nil),            // 15: teacher.GetCoursesRequest
	(*GetCoursesResponse)(nil),           // 16: teacher.GetCoursesResponse
	(*GetCourseRequest)(nil),             // 17: teacher.GetCourseRequest
	(*CourseDetailResponse)(nil),         // 18: teacher.CourseDetailResponse
	(*UpdateCourseRequest)(nil),          // 19: teacher.UpdateCourseRequest
	(*DeleteCourseRequest)(nil),          // 20: teacher.DeleteCourseRequest
	(*DeleteCourseResponse)(nil),         // 21: teacher.DeleteCourseResponse
	(*EnrollStudentRequest)(nil),         // 22: teacher.EnrollStudentRequest
	(*EnrollmentResponse)(nil),           // 23: teacher.EnrollmentResponse
	(*GetCourseEnrollmentsRequest)(nil),  // 24: teacher.GetCourseEnrollmentsRequest
	(*EnrollmentItem)(nil),               // 25: teacher.EnrollmentItem
	(*GetCourseEnrollmentsResponse)(nil), // 26: teacher.GetCourseEnrollmentsResponse
	(*GetCourseGradesRequest)(nil),       // 27: teacher.GetCourseGradesRequest
	(*StudentGradeItem)(nil),             // 28: teacher.StudentGradeItem
	(*CourseGradesResponse)(nil),         // 29: teacher.CourseGradesResponse
	(*GetTeacherDashboardRequest)(nil),   // 30: teacher.GetTeacherDashboardRequest
	(*TeacherDashboardResponse)(nil),     // 31: teacher.TeacherDashboardResponse
	(*CourseSummary)(nil),                // 32: teacher.CourseSummary
}
var file_proto_teacher_proto_depIdxs = []int32{
	5,  // 0: teacher.StudentGradesResponse.grades:type_name -> teacher.GradeItem
	13, // 1: teacher.ListTeachersResponse.teachers:type_name -> teacher.TeacherResponse
	18, // 2: teacher.GetCoursesResponse.courses:type_name -> teacher.CourseDetailResponse
	25, // 3: teacher.GetCourseEnrollmentsResponse.enrollments:type_name -> teacher.EnrollmentItem
	28, // 4: teacher.CourseGradesResponse.grades:type_name -> teacher.StudentGradeItem
	32, // 5: teacher.TeacherDashboardResponse.courses:type_name -> teacher.CourseSummary
	7,  // 6: teacher.TeacherService.CreateTeacher:input_type -> teacher.CreateTeacherRequest
	8,  // 7: teacher.TeacherService.GetTeacher:input_type -> teacher.GetTeacherRequest
	9,  // 8: teacher.TeacherService.UpdateTeacher:input_type -> teacher.UpdateTeacherRequest
	10, // 9: teacher.TeacherService.DeleteTeacher:input_type -> teacher.DeleteTeacherRequest
	12, // 10: teacher.TeacherService.ListTeachers:input_type -> teacher.ListTeachersRequest
	0,  // 11: teacher.TeacherService.CreateCourse:input_type -> teacher.CreateCourseRequest
	15, // 12: teacher.TeacherService.GetCourses:input_type -> teacher.GetCoursesRequest
	17, // 13: teacher.TeacherService.GetCourse:input_type -> teacher.GetCourseRequest
	19, // 14: teacher.TeacherService.UpdateCourse:input_type -> teacher.UpdateCourseRequest
	20, // 15: teacher.TeacherService.DeleteCourse:input_type -> teacher.DeleteCourseRequest
	22, // 16: teacher.TeacherService.EnrollStudent:input_type -> teacher.EnrollStudentRequest
	24, // 17: teacher.TeacherService.GetCourseEnrollments:input_type -> teacher.GetCourseEnrollmentsRequest
	2,  // 18: teacher.TeacherService.AssignGrade:input_type -> teacher.AssignGradeRequest
	4,  // 19: teacher.TeacherService.GetStudentGrades:input_type -> teacher.GetStudentGradesRequest
	27, // 20: teacher.TeacherService.GetCourseGrades:input_type -> teacher.GetCourseGradesRequest
	30, // 21: teacher.TeacherService.GetTeacherDashboard:input_type -> teacher.GetTeacherDashboardRequest
	13, // 22: teacher.TeacherService.CreateTeacher:output_type -> teacher.TeacherResponse
	13, // 23: teacher.TeacherService.GetTeacher:output_type -> teacher.TeacherResponse
	13, // 24: teacher.TeacherService.UpdateTeacher:output_type -> teacher.TeacherResponse
	11, // 25: teacher.TeacherService.DeleteTeacher:output_type -> teacher.DeleteTeacherResponse
	14, // 26: teacher.TeacherService.ListTeachers:output_type -> teacher.ListTeachersResponse
	1,  // 27: teacher.TeacherService.CreateCourse:output_type -> teacher.CourseResponse
	16, // 28: teacher.TeacherService.GetCourses:output_type -> teacher.GetCoursesResponse
	18, // 29: teacher.TeacherService.GetCourse:output_type -> teacher.CourseDetailResponse
	1,  // 30: teacher.TeacherService.UpdateCourse:output_type -> teacher.CourseResponse
	21, // 31: teacher.TeacherService.DeleteCourse:output_type -> teacher.DeleteCourseResponse
	23, // 32: teacher.TeacherService.EnrollStudent:output_type -> teacher.EnrollmentResponse
	26, // 33: teacher.TeacherService.GetCourseEnrollments:output_type -> teacher.GetCourseEnrollmentsResponse
	3,  // 34: teacher.TeacherService.AssignGrade:output_type -> teacher.GradeResponse
	6,  // 35: teacher.TeacherService.GetStudentGrades:output_type -> teacher.StudentGradesResponse
	29, // 36: teacher.TeacherService.GetCourseGrades:output_type -> teacher.CourseGradesResponse
	31, // 37: teacher.TeacherService.GetTeacherDashboard:output_type -> teacher.TeacherDashboardResponse
	22, // [22:38] is the sub-list for method output_type
	6,  // [6:22] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_teacher_proto_init() }
func file_proto_teacher_proto_init() {
	if File_proto_teacher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_teacher_proto_rawDesc), len(file_proto_teacher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_teacher_proto_goTypes,
		DependencyIndexes: file_proto_teacher_proto_depIdxs,
		MessageInfos:      file_proto_teacher_proto_msgTypes,
	}.Build()
	File_proto_teacher_proto = out.File
	file_proto_teacher_proto_goTypes = nil
	file_proto_teacher_proto_depIdxs = nil
}
