// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/stats.proto

package stats

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StatsService_GetPerformanceDistribution_FullMethodName = "/stats.StatsService/GetPerformanceDistribution"
	StatsService_GetAtRiskStudents_FullMethodName          = "/stats.StatsService/GetAtRiskStudents"
	StatsService_GetCategoryMastery_FullMethodName         = "/stats.StatsService/GetCategoryMastery"
	StatsService_GetCourseStats_FullMethodName             = "/stats.StatsService/GetCourseStats"
	StatsService_ReconcileGradesSync_FullMethodName        = "/stats.StatsService/ReconcileGradesSync"
	StatsService_GetStudentsAtRisk_FullMethodName          = "/stats.StatsService/GetStudentsAtRisk"
	StatsService_GetGhostStudents_FullMethodName           = "/stats.StatsService/GetGhostStudents"
	StatsService_ForecastEnrollment_FullMethodName         = "/stats.StatsService/ForecastEnrollment"
)

// StatsServiceClient is the client API for StatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatsServiceClient interface {
	// Performance Distribution - Bell Curve Data
	GetPerformanceDistribution(ctx context.Context, in *PerformanceDistributionRequest, opts ...grpc.CallOption) (*PerformanceDistributionResponse, error)
	// At-Risk Students Identification
	GetAtRiskStudents(ctx context.Context, in *AtRiskStudentsRequest, opts ...grpc.CallOption) (*AtRiskStudentsResponse, error)
	// Category Mastery Analysis
	GetCategoryMastery(ctx context.Context, in *CategoryMasteryRequest, opts ...grpc.CallOption) (*CategoryMasteryResponse, error)
	// Course Statistics Overview
	GetCourseStats(ctx context.Context, in *CourseStatsRequest, opts ...grpc.CallOption) (*CourseStatsResponse, error)
	// Reconciliation & Data Sync - Ensures stats_db matches teacher_db
	ReconcileGradesSync(ctx context.Context, in *ReconcileSyncRequest, opts ...grpc.CallOption) (*ReconcileSyncResponse, error)
	// Student Analytics (NEW)
	GetStudentsAtRisk(ctx context.Context, in *StudentsAtRiskRequest, opts ...grpc.CallOption) (*StudentsAtRiskResponse, error)
	GetGhostStudents(ctx context.Context, in *GhostStudentsRequest, opts ...grpc.CallOption) (*GhostStudentsResponse, error)
	ForecastEnrollment(ctx context.Context, in *EnrollmentForecastRequest, opts ...grpc.CallOption) (*EnrollmentForecastResponse, error)
}

type statsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatsServiceClient(cc grpc.ClientConnInterface) StatsServiceClient {
	return &statsServiceClient{cc}
}

func (c *statsServiceClient) GetPerformanceDistribution(ctx context.Context, in *PerformanceDistributionRequest, opts ...grpc.CallOption) (*PerformanceDistributionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PerformanceDistributionResponse)
	err := c.cc.Invoke(ctx, StatsService_GetPerformanceDistribution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetAtRiskStudents(ctx context.Context, in *AtRiskStudentsRequest, opts ...grpc.CallOption) (*AtRiskStudentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AtRiskStudentsResponse)
	err := c.cc.Invoke(ctx, StatsService_GetAtRiskStudents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetCategoryMastery(ctx context.Context, in *CategoryMasteryRequest, opts ...grpc.CallOption) (*CategoryMasteryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoryMasteryResponse)
	err := c.cc.Invoke(ctx, StatsService_GetCategoryMastery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetCourseStats(ctx context.Context, in *CourseStatsRequest, opts ...grpc.CallOption) (*CourseStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CourseStatsResponse)
	err := c.cc.Invoke(ctx, StatsService_GetCourseStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) ReconcileGradesSync(ctx context.Context, in *ReconcileSyncRequest, opts ...grpc.CallOption) (*ReconcileSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconcileSyncResponse)
	err := c.cc.Invoke(ctx, StatsService_ReconcileGradesSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetStudentsAtRisk(ctx context.Context, in *StudentsAtRiskRequest, opts ...grpc.CallOption) (*StudentsAtRiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudentsAtRiskResponse)
	err := c.cc.Invoke(ctx, StatsService_GetStudentsAtRisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetGhostStudents(ctx context.Context, in *GhostStudentsRequest, opts ...grpc.CallOption) (*GhostStudentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GhostStudentsResponse)
	err := c.cc.Invoke(ctx, StatsService_GetGhostStudents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) ForecastEnrollment(ctx context.Context, in *EnrollmentForecastRequest, opts ...grpc.CallOption) (*EnrollmentForecastResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollmentForecastResponse)
	err := c.cc.Invoke(ctx, StatsService_ForecastEnrollment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatsServiceServer is the server API for StatsService service.
// All implementations must embed UnimplementedStatsServiceServer
// for forward compatibility.
type StatsServiceServer interface {
	// Performance Distribution - Bell Curve Data
	GetPerformanceDistribution(context.Context, *PerformanceDistributionRequest) (*PerformanceDistributionResponse, error)
	// At-Risk Students Identification
	GetAtRiskStudents(context.Context, *AtRiskStudentsRequest) (*AtRiskStudentsResponse, error)
	// Category Mastery Analysis
	GetCategoryMastery(context.Context, *CategoryMasteryRequest) (*CategoryMasteryResponse, error)
	// Course Statistics Overview
	GetCourseStats(context.Context, *CourseStatsRequest) (*CourseStatsResponse, error)
	// Reconciliation & Data Sync - Ensures stats_db matches teacher_db
	ReconcileGradesSync(context.Context, *ReconcileSyncRequest) (*ReconcileSyncResponse, error)
	// Student Analytics (NEW)
	GetStudentsAtRisk(context.Context, *StudentsAtRiskRequest) (*StudentsAtRiskResponse, error)
	GetGhostStudents(context.Context, *GhostStudentsRequest) (*GhostStudentsResponse, error)
	ForecastEnrollment(context.Context, *EnrollmentForecastRequest) (*EnrollmentForecastResponse, error)
	mustEmbedUnimplementedStatsServiceServer()
}

// UnimplementedStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatsServiceServer struct{}

func (UnimplementedStatsServiceServer) GetPerformanceDistribution(context.Context, *PerformanceDistributionRequest) (*PerformanceDistributionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPerformanceDistribution not implemented")
}
func (UnimplementedStatsServiceServer) GetAtRiskStudents(context.Context, *AtRiskStudentsRequest) (*AtRiskStudentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAtRiskStudents not implemented")
}
func (UnimplementedStatsServiceServer) GetCategoryMastery(context.Context, *CategoryMasteryRequest) (*CategoryMasteryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategoryMastery not implemented")
}
func (UnimplementedStatsServiceServer) GetCourseStats(context.Context, *CourseStatsRequest) (*CourseStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCourseStats not implemented")
}
func (UnimplementedStatsServiceServer) ReconcileGradesSync(context.Context, *ReconcileSyncRequest) (*ReconcileSyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReconcileGradesSync not implemented")
}
func (UnimplementedStatsServiceServer) GetStudentsAtRisk(context.Context, *StudentsAtRiskRequest) (*StudentsAtRiskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStudentsAtRisk not implemented")
}
func (UnimplementedStatsServiceServer) GetGhostStudents(context.Context, *GhostStudentsRequest) (*GhostStudentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGhostStudents not implemented")
}
func (UnimplementedStatsServiceServer) ForecastEnrollment(context.Context, *EnrollmentForecastRequest) (*EnrollmentForecastResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForecastEnrollment not implemented")
}
func (UnimplementedStatsServiceServer) mustEmbedUnimplementedStatsServiceServer() {}
func (UnimplementedStatsServiceServer) testEmbeddedByValue()                      {}

// UnsafeStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatsServiceServer will
// result in compilation errors.
type UnsafeStatsServiceServer interface {
	mustEmbedUnimplementedStatsServiceServer()
}

func RegisterStatsServiceServer(s grpc.ServiceRegistrar, srv StatsServiceServer) {
	// If the following call panics, it indicates UnimplementedStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StatsService_ServiceDesc, srv)
}

func _StatsService_GetPerformanceDistribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PerformanceDistributionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetPerformanceDistribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetPerformanceDistribution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetPerformanceDistribution(ctx, req.(*PerformanceDistributionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetAtRiskStudents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AtRiskStudentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetAtRiskStudents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetAtRiskStudents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetAtRiskStudents(ctx, req.(*AtRiskStudentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetCategoryMastery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryMasteryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetCategoryMastery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetCategoryMastery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetCategoryMastery(ctx, req.(*CategoryMasteryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetCourseStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourseStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetCourseStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetCourseStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetCourseStats(ctx, req.(*CourseStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_ReconcileGradesSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconcileSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).ReconcileGradesSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_ReconcileGradesSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).ReconcileGradesSync(ctx, req.(*ReconcileSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetStudentsAtRisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentsAtRiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetStudentsAtRisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetStudentsAtRisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetStudentsAtRisk(ctx, req.(*StudentsAtRiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetGhostStudents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GhostStudentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetGhostStudents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetGhostStudents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetGhostStudents(ctx, req.(*GhostStudentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_ForecastEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollmentForecastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).ForecastEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_ForecastEnrollment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).ForecastEnrollment(ctx, req.(*EnrollmentForecastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatsService_ServiceDesc is the grpc.ServiceDesc for StatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stats.StatsService",
	HandlerType: (*StatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPerformanceDistribution",
			Handler:    _StatsService_GetPerformanceDistribution_Handler,
		},
		{
			MethodName: "GetAtRiskStudents",
			Handler:    _StatsService_GetAtRiskStudents_Handler,
		},
		{
			MethodName: "GetCategoryMastery",
			Handler:    _StatsService_GetCategoryMastery_Handler,
		},
		{
			MethodName: "GetCourseStats",
			Handler:    _StatsService_GetCourseStats_Handler,
		},
		{
			MethodName: "ReconcileGradesSync",
			Handler:    _StatsService_ReconcileGradesSync_Handler,
		},
		{
			MethodName: "GetStudentsAtRisk",
			Handler:    _StatsService_GetStudentsAtRisk_Handler,
		},
		{
			MethodName: "GetGhostStudents",
			Handler:    _StatsService_GetGhostStudents_Handler,
		},
		{
			MethodName: "ForecastEnrollment",
			Handler:    _StatsService_ForecastEnrollment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/stats.proto",
}
