// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/school.proto

package school

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SchoolService_LoginAdmin_FullMethodName                = "/school.SchoolService/LoginAdmin"
	SchoolService_CreateAdmin_FullMethodName               = "/school.SchoolService/CreateAdmin"
	SchoolService_GetAdmin_FullMethodName                  = "/school.SchoolService/GetAdmin"
	SchoolService_UpdateAdmin_FullMethodName               = "/school.SchoolService/UpdateAdmin"
	SchoolService_DeleteAdmin_FullMethodName               = "/school.SchoolService/DeleteAdmin"
	SchoolService_ListAdmins_FullMethodName                = "/school.SchoolService/ListAdmins"
	SchoolService_CreateSchool_FullMethodName              = "/school.SchoolService/CreateSchool"
	SchoolService_GetSchool_FullMethodName                 = "/school.SchoolService/GetSchool"
	SchoolService_UpdateSchool_FullMethodName              = "/school.SchoolService/UpdateSchool"
	SchoolService_DeleteSchool_FullMethodName              = "/school.SchoolService/DeleteSchool"
	SchoolService_ListSchools_FullMethodName               = "/school.SchoolService/ListSchools"
	SchoolService_CreateClass_FullMethodName               = "/school.SchoolService/CreateClass"
	SchoolService_GetClass_FullMethodName                  = "/school.SchoolService/GetClass"
	SchoolService_UpdateClass_FullMethodName               = "/school.SchoolService/UpdateClass"
	SchoolService_DeleteClass_FullMethodName               = "/school.SchoolService/DeleteClass"
	SchoolService_ListClasses_FullMethodName               = "/school.SchoolService/ListClasses"
	SchoolService_CreateCourse_FullMethodName              = "/school.SchoolService/CreateCourse"
	SchoolService_GetCourse_FullMethodName                 = "/school.SchoolService/GetCourse"
	SchoolService_UpdateCourse_FullMethodName              = "/school.SchoolService/UpdateCourse"
	SchoolService_DeleteCourse_FullMethodName              = "/school.SchoolService/DeleteCourse"
	SchoolService_ListCourses_FullMethodName               = "/school.SchoolService/ListCourses"
	SchoolService_GetTeacherCourseList_FullMethodName      = "/school.SchoolService/GetTeacherCourseList"
	SchoolService_AssignTeacherToCourse_FullMethodName     = "/school.SchoolService/AssignTeacherToCourse"
	SchoolService_UnassignTeacherFromCourse_FullMethodName = "/school.SchoolService/UnassignTeacherFromCourse"
	SchoolService_GetCourseTeachers_FullMethodName         = "/school.SchoolService/GetCourseTeachers"
	SchoolService_EnrollStudent_FullMethodName             = "/school.SchoolService/EnrollStudent"
	SchoolService_UnenrollStudent_FullMethodName           = "/school.SchoolService/UnenrollStudent"
	SchoolService_GetCourseEnrollments_FullMethodName      = "/school.SchoolService/GetCourseEnrollments"
	SchoolService_GetStudentEnrollments_FullMethodName     = "/school.SchoolService/GetStudentEnrollments"
	SchoolService_ValidateCourseExists_FullMethodName      = "/school.SchoolService/ValidateCourseExists"
)

// SchoolServiceClient is the client API for SchoolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchoolServiceClient interface {
	// Authentication
	LoginAdmin(ctx context.Context, in *LoginAdminRequest, opts ...grpc.CallOption) (*LoginAdminResponse, error)
	// Admin CRUD
	CreateAdmin(ctx context.Context, in *CreateAdminRequest, opts ...grpc.CallOption) (*AdminResponse, error)
	GetAdmin(ctx context.Context, in *GetAdminRequest, opts ...grpc.CallOption) (*AdminResponse, error)
	UpdateAdmin(ctx context.Context, in *UpdateAdminRequest, opts ...grpc.CallOption) (*AdminResponse, error)
	DeleteAdmin(ctx context.Context, in *DeleteAdminRequest, opts ...grpc.CallOption) (*DeleteAdminResponse, error)
	ListAdmins(ctx context.Context, in *ListAdminsRequest, opts ...grpc.CallOption) (*ListAdminsResponse, error)
	// School CRUD
	CreateSchool(ctx context.Context, in *CreateSchoolRequest, opts ...grpc.CallOption) (*SchoolResponse, error)
	GetSchool(ctx context.Context, in *GetSchoolRequest, opts ...grpc.CallOption) (*SchoolResponse, error)
	UpdateSchool(ctx context.Context, in *UpdateSchoolRequest, opts ...grpc.CallOption) (*SchoolResponse, error)
	DeleteSchool(ctx context.Context, in *DeleteSchoolRequest, opts ...grpc.CallOption) (*DeleteSchoolResponse, error)
	ListSchools(ctx context.Context, in *ListSchoolsRequest, opts ...grpc.CallOption) (*ListSchoolsResponse, error)
	// Class CRUD
	CreateClass(ctx context.Context, in *CreateClassRequest, opts ...grpc.CallOption) (*ClassResponse, error)
	GetClass(ctx context.Context, in *GetClassRequest, opts ...grpc.CallOption) (*ClassResponse, error)
	UpdateClass(ctx context.Context, in *UpdateClassRequest, opts ...grpc.CallOption) (*ClassResponse, error)
	DeleteClass(ctx context.Context, in *DeleteClassRequest, opts ...grpc.CallOption) (*DeleteClassResponse, error)
	ListClasses(ctx context.Context, in *ListClassesRequest, opts ...grpc.CallOption) (*ListClassesResponse, error)
	// Course Management (Admin only)
	CreateCourse(ctx context.Context, in *CreateCourseRequest, opts ...grpc.CallOption) (*CourseResponse, error)
	GetCourse(ctx context.Context, in *GetCourseRequest, opts ...grpc.CallOption) (*CourseDetailResponse, error)
	UpdateCourse(ctx context.Context, in *UpdateCourseRequest, opts ...grpc.CallOption) (*CourseResponse, error)
	DeleteCourse(ctx context.Context, in *DeleteCourseRequest, opts ...grpc.CallOption) (*DeleteCourseResponse, error)
	ListCourses(ctx context.Context, in *ListCoursesRequest, opts ...grpc.CallOption) (*ListCoursesResponse, error)
	GetTeacherCourseList(ctx context.Context, in *GetTeacherCourseListRequest, opts ...grpc.CallOption) (*GetTeacherCourseListResponse, error)
	// Course-Teacher Assignment (Admin only)
	AssignTeacherToCourse(ctx context.Context, in *AssignTeacherToCourseRequest, opts ...grpc.CallOption) (*AssignmentResponse, error)
	UnassignTeacherFromCourse(ctx context.Context, in *UnassignTeacherRequest, opts ...grpc.CallOption) (*UnassignmentResponse, error)
	GetCourseTeachers(ctx context.Context, in *GetCourseTeachersRequest, opts ...grpc.CallOption) (*CourseTeachersResponse, error)
	// Enrollment Management
	EnrollStudent(ctx context.Context, in *EnrollStudentRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error)
	UnenrollStudent(ctx context.Context, in *UnenrollStudentRequest, opts ...grpc.CallOption) (*UnenrollmentResponse, error)
	GetCourseEnrollments(ctx context.Context, in *GetCourseEnrollmentsRequest, opts ...grpc.CallOption) (*CourseEnrollmentsResponse, error)
	GetStudentEnrollments(ctx context.Context, in *GetStudentEnrollmentsRequest, opts ...grpc.CallOption) (*StudentEnrollmentsResponse, error)
	ValidateCourseExists(ctx context.Context, in *ValidateCourseRequest, opts ...grpc.CallOption) (*ValidateCourseResponse, error)
}

type schoolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSchoolServiceClient(cc grpc.ClientConnInterface) SchoolServiceClient {
	return &schoolServiceClient{cc}
}

func (c *schoolServiceClient) LoginAdmin(ctx context.Context, in *LoginAdminRequest, opts ...grpc.CallOption) (*LoginAdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginAdminResponse)
	err := c.cc.Invoke(ctx, SchoolService_LoginAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) CreateAdmin(ctx context.Context, in *CreateAdminRequest, opts ...grpc.CallOption) (*AdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminResponse)
	err := c.cc.Invoke(ctx, SchoolService_CreateAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) GetAdmin(ctx context.Context, in *GetAdminRequest, opts ...grpc.CallOption) (*AdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminResponse)
	err := c.cc.Invoke(ctx, SchoolService_GetAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) UpdateAdmin(ctx context.Context, in *UpdateAdminRequest, opts ...grpc.CallOption) (*AdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminResponse)
	err := c.cc.Invoke(ctx, SchoolService_UpdateAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) DeleteAdmin(ctx context.Context, in *DeleteAdminRequest, opts ...grpc.CallOption) (*DeleteAdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAdminResponse)
	err := c.cc.Invoke(ctx, SchoolService_DeleteAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) ListAdmins(ctx context.Context, in *ListAdminsRequest, opts ...grpc.CallOption) (*ListAdminsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminsResponse)
	err := c.cc.Invoke(ctx, SchoolService_ListAdmins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) CreateSchool(ctx context.Context, in *CreateSchoolRequest, opts ...grpc.CallOption) (*SchoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchoolResponse)
	err := c.cc.Invoke(ctx, SchoolService_CreateSchool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) GetSchool(ctx context.Context, in *GetSchoolRequest, opts ...grpc.CallOption) (*SchoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchoolResponse)
	err := c.cc.Invoke(ctx, SchoolService_GetSchool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) UpdateSchool(ctx context.Context, in *UpdateSchoolRequest, opts ...grpc.CallOption) (*SchoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchoolResponse)
	err := c.cc.Invoke(ctx, SchoolService_UpdateSchool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) DeleteSchool(ctx context.Context, in *DeleteSchoolRequest, opts ...grpc.CallOption) (*DeleteSchoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSchoolResponse)
	err := c.cc.Invoke(ctx, SchoolService_DeleteSchool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) ListSchools(ctx context.Context, in *ListSchoolsRequest, opts ...grpc.CallOption) (*ListSchoolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSchoolsResponse)
	err := c.cc.Invoke(ctx, SchoolService_ListSchools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) CreateClass(ctx context.Context, in *CreateClassRequest, opts ...grpc.CallOption) (*ClassResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassResponse)
	err := c.cc.Invoke(ctx, SchoolService_CreateClass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) GetClass(ctx context.Context, in *GetClassRequest, opts ...grpc.CallOption) (*ClassResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassResponse)
	err := c.cc.Invoke(ctx, SchoolService_GetClass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) UpdateClass(ctx context.Context, in *UpdateClassRequest, opts ...grpc.CallOption) (*ClassResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassResponse)
	err := c.cc.Invoke(ctx, SchoolService_UpdateClass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) DeleteClass(ctx context.Context, in *DeleteClassRequest, opts ...grpc.CallOption) (*DeleteClassResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteClassResponse)
	err := c.cc.Invoke(ctx, SchoolService_DeleteClass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) ListClasses(ctx context.Context, in *ListClassesRequest, opts ...grpc.CallOption) (*ListClassesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListClassesResponse)
	err := c.cc.Invoke(ctx, SchoolService_ListClasses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) CreateCourse(ctx context.Context, in *CreateCourseRequest, opts ...grpc.CallOption) (*CourseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CourseResponse)
	err := c.cc.Invoke(ctx, SchoolService_CreateCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) GetCourse(ctx context.Context, in *GetCourseRequest, opts ...grpc.CallOption) (*CourseDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CourseDetailResponse)
	err := c.cc.Invoke(ctx, SchoolService_GetCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) UpdateCourse(ctx context.Context, in *UpdateCourseRequest, opts ...grpc.CallOption) (*CourseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CourseResponse)
	err := c.cc.Invoke(ctx, SchoolService_UpdateCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) DeleteCourse(ctx context.Context, in *DeleteCourseRequest, opts ...grpc.CallOption) (*DeleteCourseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCourseResponse)
	err := c.cc.Invoke(ctx, SchoolService_DeleteCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) ListCourses(ctx context.Context, in *ListCoursesRequest, opts ...grpc.CallOption) (*ListCoursesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCoursesResponse)
	err := c.cc.Invoke(ctx, SchoolService_ListCourses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) GetTeacherCourseList(ctx context.Context, in *GetTeacherCourseListRequest, opts ...grpc.CallOption) (*GetTeacherCourseListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTeacherCourseListResponse)
	err := c.cc.Invoke(ctx, SchoolService_GetTeacherCourseList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) AssignTeacherToCourse(ctx context.Context, in *AssignTeacherToCourseRequest, opts ...grpc.CallOption) (*AssignmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignmentResponse)
	err := c.cc.Invoke(ctx, SchoolService_AssignTeacherToCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) UnassignTeacherFromCourse(ctx context.Context, in *UnassignTeacherRequest, opts ...grpc.CallOption) (*UnassignmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnassignmentResponse)
	err := c.cc.Invoke(ctx, SchoolService_UnassignTeacherFromCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) GetCourseTeachers(ctx context.Context, in *GetCourseTeachersRequest, opts ...grpc.CallOption) (*CourseTeachersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CourseTeachersResponse)
	err := c.cc.Invoke(ctx, SchoolService_GetCourseTeachers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) EnrollStudent(ctx context.Context, in *EnrollStudentRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollmentResponse)
	err := c.cc.Invoke(ctx, SchoolService_EnrollStudent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) UnenrollStudent(ctx context.Context, in *UnenrollStudentRequest, opts ...grpc.CallOption) (*UnenrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnenrollmentResponse)
	err := c.cc.Invoke(ctx, SchoolService_UnenrollStudent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) GetCourseEnrollments(ctx context.Context, in *GetCourseEnrollmentsRequest, opts ...grpc.CallOption) (*CourseEnrollmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CourseEnrollmentsResponse)
	err := c.cc.Invoke(ctx, SchoolService_GetCourseEnrollments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) GetStudentEnrollments(ctx context.Context, in *GetStudentEnrollmentsRequest, opts ...grpc.CallOption) (*StudentEnrollmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudentEnrollmentsResponse)
	err := c.cc.Invoke(ctx, SchoolService_GetStudentEnrollments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schoolServiceClient) ValidateCourseExists(ctx context.Context, in *ValidateCourseRequest, opts ...grpc.CallOption) (*ValidateCourseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateCourseResponse)
	err := c.cc.Invoke(ctx, SchoolService_ValidateCourseExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchoolServiceServer is the server API for SchoolService service.
// All implementations must embed UnimplementedSchoolServiceServer
// for forward compatibility.
type SchoolServiceServer interface {
	// Authentication
	LoginAdmin(context.Context, *LoginAdminRequest) (*LoginAdminResponse, error)
	// Admin CRUD
	CreateAdmin(context.Context, *CreateAdminRequest) (*AdminResponse, error)
	GetAdmin(context.Context, *GetAdminRequest) (*AdminResponse, error)
	UpdateAdmin(context.Context, *UpdateAdminRequest) (*AdminResponse, error)
	DeleteAdmin(context.Context, *DeleteAdminRequest) (*DeleteAdminResponse, error)
	ListAdmins(context.Context, *ListAdminsRequest) (*ListAdminsResponse, error)
	// School CRUD
	CreateSchool(context.Context, *CreateSchoolRequest) (*SchoolResponse, error)
	GetSchool(context.Context, *GetSchoolRequest) (*SchoolResponse, error)
	UpdateSchool(context.Context, *UpdateSchoolRequest) (*SchoolResponse, error)
	DeleteSchool(context.Context, *DeleteSchoolRequest) (*DeleteSchoolResponse, error)
	ListSchools(context.Context, *ListSchoolsRequest) (*ListSchoolsResponse, error)
	// Class CRUD
	CreateClass(context.Context, *CreateClassRequest) (*ClassResponse, error)
	GetClass(context.Context, *GetClassRequest) (*ClassResponse, error)
	UpdateClass(context.Context, *UpdateClassRequest) (*ClassResponse, error)
	DeleteClass(context.Context, *DeleteClassRequest) (*DeleteClassResponse, error)
	ListClasses(context.Context, *ListClassesRequest) (*ListClassesResponse, error)
	// Course Management (Admin only)
	CreateCourse(context.Context, *CreateCourseRequest) (*CourseResponse, error)
	GetCourse(context.Context, *GetCourseRequest) (*CourseDetailResponse, error)
	UpdateCourse(context.Context, *UpdateCourseRequest) (*CourseResponse, error)
	DeleteCourse(context.Context, *DeleteCourseRequest) (*DeleteCourseResponse, error)
	ListCourses(context.Context, *ListCoursesRequest) (*ListCoursesResponse, error)
	GetTeacherCourseList(context.Context, *GetTeacherCourseListRequest) (*GetTeacherCourseListResponse, error)
	// Course-Teacher Assignment (Admin only)
	AssignTeacherToCourse(context.Context, *AssignTeacherToCourseRequest) (*AssignmentResponse, error)
	UnassignTeacherFromCourse(context.Context, *UnassignTeacherRequest) (*UnassignmentResponse, error)
	GetCourseTeachers(context.Context, *GetCourseTeachersRequest) (*CourseTeachersResponse, error)
	// Enrollment Management
	EnrollStudent(context.Context, *EnrollStudentRequest) (*EnrollmentResponse, error)
	UnenrollStudent(context.Context, *UnenrollStudentRequest) (*UnenrollmentResponse, error)
	GetCourseEnrollments(context.Context, *GetCourseEnrollmentsRequest) (*CourseEnrollmentsResponse, error)
	GetStudentEnrollments(context.Context, *GetStudentEnrollmentsRequest) (*StudentEnrollmentsResponse, error)
	ValidateCourseExists(context.Context, *ValidateCourseRequest) (*ValidateCourseResponse, error)
	mustEmbedUnimplementedSchoolServiceServer()
}

// UnimplementedSchoolServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchoolServiceServer struct{}

func (UnimplementedSchoolServiceServer) LoginAdmin(context.Context, *LoginAdminRequest) (*LoginAdminResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginAdmin not implemented")
}
func (UnimplementedSchoolServiceServer) CreateAdmin(context.Context, *CreateAdminRequest) (*AdminResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAdmin not implemented")
}
func (UnimplementedSchoolServiceServer) GetAdmin(context.Context, *GetAdminRequest) (*AdminResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdmin not implemented")
}
func (UnimplementedSchoolServiceServer) UpdateAdmin(context.Context, *UpdateAdminRequest) (*AdminResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAdmin not implemented")
}
func (UnimplementedSchoolServiceServer) DeleteAdmin(context.Context, *DeleteAdminRequest) (*DeleteAdminResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAdmin not implemented")
}
func (UnimplementedSchoolServiceServer) ListAdmins(context.Context, *ListAdminsRequest) (*ListAdminsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdmins not implemented")
}
func (UnimplementedSchoolServiceServer) CreateSchool(context.Context, *CreateSchoolRequest) (*SchoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSchool not implemented")
}
func (UnimplementedSchoolServiceServer) GetSchool(context.Context, *GetSchoolRequest) (*SchoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchool not implemented")
}
func (UnimplementedSchoolServiceServer) UpdateSchool(context.Context, *UpdateSchoolRequest) (*SchoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSchool not implemented")
}
func (UnimplementedSchoolServiceServer) DeleteSchool(context.Context, *DeleteSchoolRequest) (*DeleteSchoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSchool not implemented")
}
func (UnimplementedSchoolServiceServer) ListSchools(context.Context, *ListSchoolsRequest) (*ListSchoolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSchools not implemented")
}
func (UnimplementedSchoolServiceServer) CreateClass(context.Context, *CreateClassRequest) (*ClassResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateClass not implemented")
}
func (UnimplementedSchoolServiceServer) GetClass(context.Context, *GetClassRequest) (*ClassResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClass not implemented")
}
func (UnimplementedSchoolServiceServer) UpdateClass(context.Context, *UpdateClassRequest) (*ClassResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateClass not implemented")
}
func (UnimplementedSchoolServiceServer) DeleteClass(context.Context, *DeleteClassRequest) (*DeleteClassResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteClass not implemented")
}
func (UnimplementedSchoolServiceServer) ListClasses(context.Context, *ListClassesRequest) (*ListClassesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListClasses not implemented")
}
func (UnimplementedSchoolServiceServer) CreateCourse(context.Context, *CreateCourseRequest) (*CourseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCourse not implemented")
}
func (UnimplementedSchoolServiceServer) GetCourse(context.Context, *GetCourseRequest) (*CourseDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCourse not implemented")
}
func (UnimplementedSchoolServiceServer) UpdateCourse(context.Context, *UpdateCourseRequest) (*CourseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCourse not implemented")
}
func (UnimplementedSchoolServiceServer) DeleteCourse(context.Context, *DeleteCourseRequest) (*DeleteCourseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCourse not implemented")
}
func (UnimplementedSchoolServiceServer) ListCourses(context.Context, *ListCoursesRequest) (*ListCoursesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCourses not implemented")
}
func (UnimplementedSchoolServiceServer) GetTeacherCourseList(context.Context, *GetTeacherCourseListRequest) (*GetTeacherCourseListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTeacherCourseList not implemented")
}
func (UnimplementedSchoolServiceServer) AssignTeacherToCourse(context.Context, *AssignTeacherToCourseRequest) (*AssignmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignTeacherToCourse not implemented")
}
func (UnimplementedSchoolServiceServer) UnassignTeacherFromCourse(context.Context, *UnassignTeacherRequest) (*UnassignmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnassignTeacherFromCourse not implemented")
}
func (UnimplementedSchoolServiceServer) GetCourseTeachers(context.Context, *GetCourseTeachersRequest) (*CourseTeachersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCourseTeachers not implemented")
}
func (UnimplementedSchoolServiceServer) EnrollStudent(context.Context, *EnrollStudentRequest) (*EnrollmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrollStudent not implemented")
}
func (UnimplementedSchoolServiceServer) UnenrollStudent(context.Context, *UnenrollStudentRequest) (*UnenrollmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnenrollStudent not implemented")
}
func (UnimplementedSchoolServiceServer) GetCourseEnrollments(context.Context, *GetCourseEnrollmentsRequest) (*CourseEnrollmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCourseEnrollments not implemented")
}
func (UnimplementedSchoolServiceServer) GetStudentEnrollments(context.Context, *GetStudentEnrollmentsRequest) (*StudentEnrollmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStudentEnrollments not implemented")
}
func (UnimplementedSchoolServiceServer) ValidateCourseExists(context.Context, *ValidateCourseRequest) (*ValidateCourseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateCourseExists not implemented")
}
func (UnimplementedSchoolServiceServer) mustEmbedUnimplementedSchoolServiceServer() {}
func (UnimplementedSchoolServiceServer) testEmbeddedByValue()                       {}

// UnsafeSchoolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchoolServiceServer will
// result in compilation errors.
type UnsafeSchoolServiceServer interface {
	mustEmbedUnimplementedSchoolServiceServer()
}

func RegisterSchoolServiceServer(s grpc.ServiceRegistrar, srv SchoolServiceServer) {
	// If the following call panics, it indicates UnimplementedSchoolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SchoolService_ServiceDesc, srv)
}

func _SchoolService_LoginAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).LoginAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_LoginAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).LoginAdmin(ctx, req.(*LoginAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_CreateAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).CreateAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_CreateAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).CreateAdmin(ctx, req.(*CreateAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_GetAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).GetAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_GetAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).GetAdmin(ctx, req.(*GetAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_UpdateAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).UpdateAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_UpdateAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).UpdateAdmin(ctx, req.(*UpdateAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_DeleteAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).DeleteAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_DeleteAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).DeleteAdmin(ctx, req.(*DeleteAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_ListAdmins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).ListAdmins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_ListAdmins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).ListAdmins(ctx, req.(*ListAdminsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_CreateSchool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSchoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).CreateSchool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_CreateSchool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).CreateSchool(ctx, req.(*CreateSchoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_GetSchool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).GetSchool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_GetSchool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).GetSchool(ctx, req.(*GetSchoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_UpdateSchool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSchoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).UpdateSchool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_UpdateSchool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).UpdateSchool(ctx, req.(*UpdateSchoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_DeleteSchool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSchoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).DeleteSchool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_DeleteSchool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).DeleteSchool(ctx, req.(*DeleteSchoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_ListSchools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSchoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).ListSchools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_ListSchools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).ListSchools(ctx, req.(*ListSchoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_CreateClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).CreateClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_CreateClass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).CreateClass(ctx, req.(*CreateClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_GetClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).GetClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_GetClass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).GetClass(ctx, req.(*GetClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_UpdateClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).UpdateClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_UpdateClass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).UpdateClass(ctx, req.(*UpdateClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_DeleteClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).DeleteClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_DeleteClass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).DeleteClass(ctx, req.(*DeleteClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_ListClasses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClassesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).ListClasses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_ListClasses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).ListClasses(ctx, req.(*ListClassesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_CreateCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).CreateCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_CreateCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).CreateCourse(ctx, req.(*CreateCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_GetCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).GetCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_GetCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).GetCourse(ctx, req.(*GetCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_UpdateCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).UpdateCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_UpdateCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).UpdateCourse(ctx, req.(*UpdateCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_DeleteCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).DeleteCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_DeleteCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).DeleteCourse(ctx, req.(*DeleteCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_ListCourses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCoursesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).ListCourses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_ListCourses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).ListCourses(ctx, req.(*ListCoursesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_GetTeacherCourseList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeacherCourseListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).GetTeacherCourseList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_GetTeacherCourseList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).GetTeacherCourseList(ctx, req.(*GetTeacherCourseListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_AssignTeacherToCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignTeacherToCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).AssignTeacherToCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_AssignTeacherToCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).AssignTeacherToCourse(ctx, req.(*AssignTeacherToCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_UnassignTeacherFromCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnassignTeacherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).UnassignTeacherFromCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_UnassignTeacherFromCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).UnassignTeacherFromCourse(ctx, req.(*UnassignTeacherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_GetCourseTeachers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseTeachersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).GetCourseTeachers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_GetCourseTeachers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).GetCourseTeachers(ctx, req.(*GetCourseTeachersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_EnrollStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).EnrollStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_EnrollStudent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).EnrollStudent(ctx, req.(*EnrollStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_UnenrollStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnenrollStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).UnenrollStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_UnenrollStudent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).UnenrollStudent(ctx, req.(*UnenrollStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_GetCourseEnrollments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseEnrollmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).GetCourseEnrollments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_GetCourseEnrollments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).GetCourseEnrollments(ctx, req.(*GetCourseEnrollmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_GetStudentEnrollments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentEnrollmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).GetStudentEnrollments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_GetStudentEnrollments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).GetStudentEnrollments(ctx, req.(*GetStudentEnrollmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchoolService_ValidateCourseExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchoolServiceServer).ValidateCourseExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchoolService_ValidateCourseExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchoolServiceServer).ValidateCourseExists(ctx, req.(*ValidateCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SchoolService_ServiceDesc is the grpc.ServiceDesc for SchoolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchoolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "school.SchoolService",
	HandlerType: (*SchoolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginAdmin",
			Handler:    _SchoolService_LoginAdmin_Handler,
		},
		{
			MethodName: "CreateAdmin",
			Handler:    _SchoolService_CreateAdmin_Handler,
		},
		{
			MethodName: "GetAdmin",
			Handler:    _SchoolService_GetAdmin_Handler,
		},
		{
			MethodName: "UpdateAdmin",
			Handler:    _SchoolService_UpdateAdmin_Handler,
		},
		{
			MethodName: "DeleteAdmin",
			Handler:    _SchoolService_DeleteAdmin_Handler,
		},
		{
			MethodName: "ListAdmins",
			Handler:    _SchoolService_ListAdmins_Handler,
		},
		{
			MethodName: "CreateSchool",
			Handler:    _SchoolService_CreateSchool_Handler,
		},
		{
			MethodName: "GetSchool",
			Handler:    _SchoolService_GetSchool_Handler,
		},
		{
			MethodName: "UpdateSchool",
			Handler:    _SchoolService_UpdateSchool_Handler,
		},
		{
			MethodName: "DeleteSchool",
			Handler:    _SchoolService_DeleteSchool_Handler,
		},
		{
			MethodName: "ListSchools",
			Handler:    _SchoolService_ListSchools_Handler,
		},
		{
			MethodName: "CreateClass",
			Handler:    _SchoolService_CreateClass_Handler,
		},
		{
			MethodName: "GetClass",
			Handler:    _SchoolService_GetClass_Handler,
		},
		{
			MethodName: "UpdateClass",
			Handler:    _SchoolService_UpdateClass_Handler,
		},
		{
			MethodName: "DeleteClass",
			Handler:    _SchoolService_DeleteClass_Handler,
		},
		{
			MethodName: "ListClasses",
			Handler:    _SchoolService_ListClasses_Handler,
		},
		{
			MethodName: "CreateCourse",
			Handler:    _SchoolService_CreateCourse_Handler,
		},
		{
			MethodName: "GetCourse",
			Handler:    _SchoolService_GetCourse_Handler,
		},
		{
			MethodName: "UpdateCourse",
			Handler:    _SchoolService_UpdateCourse_Handler,
		},
		{
			MethodName: "DeleteCourse",
			Handler:    _SchoolService_DeleteCourse_Handler,
		},
		{
			MethodName: "ListCourses",
			Handler:    _SchoolService_ListCourses_Handler,
		},
		{
			MethodName: "GetTeacherCourseList",
			Handler:    _SchoolService_GetTeacherCourseList_Handler,
		},
		{
			MethodName: "AssignTeacherToCourse",
			Handler:    _SchoolService_AssignTeacherToCourse_Handler,
		},
		{
			MethodName: "UnassignTeacherFromCourse",
			Handler:    _SchoolService_UnassignTeacherFromCourse_Handler,
		},
		{
			MethodName: "GetCourseTeachers",
			Handler:    _SchoolService_GetCourseTeachers_Handler,
		},
		{
			MethodName: "EnrollStudent",
			Handler:    _SchoolService_EnrollStudent_Handler,
		},
		{
			MethodName: "UnenrollStudent",
			Handler:    _SchoolService_UnenrollStudent_Handler,
		},
		{
			MethodName: "GetCourseEnrollments",
			Handler:    _SchoolService_GetCourseEnrollments_Handler,
		},
		{
			MethodName: "GetStudentEnrollments",
			Handler:    _SchoolService_GetStudentEnrollments_Handler,
		},
		{
			MethodName: "ValidateCourseExists",
			Handler:    _SchoolService_ValidateCourseExists_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/school.proto",
}
